import argparse
import requests
from rsshistory.webtools import WebConfig

domain_list = """
https://rsa-al.gov
https://rulewatchohio.gov
https://safeandsoundiowa.gov
https://safeathomeohio.gov
https://safeathomewi.gov
https://safehomealabama.gov
https://safemt.gov
https://safesd.gov
https://safestayok.gov
https://safetyworksmaine.gov
https://saomt.gov
https://save4lateriowa.gov
https://saveourhomeaz.gov
https://savethedreamohio.gov
https://scag.gov
https://scconsumer.gov
https://scdew.gov
https://scdhec.gov
https://scdhhs.gov
https://scdot.gov
https://scdps.gov
https://scfc.gov
https://sc.gov
https://scmedicaid.gov
https://scohio.gov
https://scserv.gov
https://sctib.gov
https://sdauditor.gov
https://sdbehavioralhealth.gov
https://sdbmoe.gov
https://sd.gov
https://sdlegislature.gov
https://sdresponse.gov
https://sdsos.gov
https://sdtreasurer.gov
https://sentineltx.gov
https://servealabama.gov
https://serveidaho.gov
https://serveindiana.gov
https://servend.gov
https://serveohio.gov
https://servga.gov
https://servicearizona.gov
https://sflhidta.gov
https://sfwmd.gov
https://shapesouthcarolina.gov
https://siliconheartlandohio.gov
https://skillsenhancementtexas.gov
https://skillsenhancementtx.gov
https://slfpae.gov
https://smartinvestks.gov
https://sorwi.gov
https://sosmt.gov
https://sosnc.gov
https://sourcewell-mn.gov
https://southcarolina.gov
https://stagingaz.gov
https://statelibraryofiowa.gov
https://stateofsouthcarolina.gov
https://stateofwv.gov
https://stopfraudcolorado.gov
https://strongohio.gov
https://sunbizflorida.gov
https://supremecourtofohio.gov
https://surplustexas.gov
https://takechargetexas.gov
https://teachiowa.gov
https://teamga.gov
https://teamgeorgia.gov
https://teamtn.gov
https://tenncare.gov
https://tennesseeda.gov
https://tennessee.gov
https://tennesseeiis.gov
https://tennesseepromise.gov
https://tennesseereconnect.gov
https://testazdes.gov
https://testiowa.gov
https://testnd.gov
https://testohio.gov
https://texasagriculture.gov
https://texasassessment.gov
https://texasattorneygeneral.gov
https://texasbulliondepository.gov
https://texaschildrenscommission.gov
https://texascourthelp.gov
https://texasfightsidtheft.gov
https://texas.gov
https://texasisao.gov
https://texasjcmh.gov
https://texasonline.gov
https://texasready.gov
https://texasschools.gov
https://texasstateparks.gov
https://texassupremecourtcommission.gov
https://texassurplus.gov
https://texdot.gov
https://thecometsc.gov
https://theftaz.gov
https://thestateofsouthcarolina.gov
https://tnbestforall.gov
https://tncollateralmanagement.gov
https://tncourts.gov
https://tndagc.gov
https://tnecd.gov
https://tnedu.gov
https://tnfafsafrenzy.gov
https://tnfosters.gov
https://tn.gov
https://tnhighwaypatrol.gov
https://tnk12.gov
https://tnlpr.gov
https://tnosha.gov
https://tnpromise.gov
https://tnrealid.gov
https://tnreconnect.gov
https://tnsos.gov
https://tntapinfo.gov
https://tntreasury.gov
https://tnusedoil.gov
https://tnvacation.gov
https://tnwildlandfire.gov
https://tourismohio.gov
https://townofbutlerwi.gov
https://townofreseburgwi.gov
https://townofwordenwi.gov
https://transparencyflorida.gov
https://travelwyoming.gov
https://truckingks.gov
https://trusttennessee.gov
https://trusttn.gov
https://tudinerori.gov
https://txag.gov
https://txassessment.gov
https://txbd.gov
https://txbulliondepository.gov
https://txcourts.gov
https://txdmv.gov
https://txdot.gov
https://tx.gov
https://txisao.gov
https://txoag.gov
https://txschools.gov
https://txsmartbids.gov
https://txsmartbuy.gov
https://utah.gov
https://utcourts.gov
https://vacourts.gov
https://vaemergency.gov
https://vamoneysearch.gov
https://vatax.gov
https://vawildlife.gov
https://vayavotarcolorado.gov
https://vermont.gov
https://vermonthealthconnect.gov
https://vermonttreasurer.gov
https://vidol.gov
https://vi.gov
https://vihfa.gov
https://villageofeastaltonil.gov
https://villageoftheresawi.gov
https://villageofwitheewi.gov
https://virginiaabc.gov
https://virginiacapital.gov
https://virginiacapitol.gov
https://virginiageneralassembly.gov
https://virginia.gov
https://virginiaresources.gov
https://virginiastateparks.gov
https://virginiawildlife.gov
https://virginiaworks.gov
https://visitidaho.gov
https://visitnebraska.gov
https://visitnh.gov
https://visitwyo.gov
https://visitwyoming.gov
https://volunteerlouisiana.gov
https://volunteermaine.gov
https://votemt.gov
https://vtalert.gov
https://vt.gov
https://vtjud.gov
https://vtleg.gov
https://wa.gov
https://wallacecountyks.gov
https://washingtondc.gov
https://washington.gov
https://washingtonstate.gov
https://waworkzonespeedcameras.gov
https://welcometoohio.gov
https://westcomm-ma.gov
https://westvirginia.gov
https://wfnj.gov
https://wibadgertracs.gov
https://wiconnections2030.gov
https://wicourts.gov
https://widatcp.gov
https://widma.gov
https://widoc.gov
https://widoj.gov
https://wi.gov
https://wigrants.gov
https://wilawlibrary.gov
https://wildohio.gov
https://wisc.gov
https://wisconsincrimealert.gov
https://wisconsindmv.gov
https://wisconsindot.gov
https://wisconsinfreightplan.gov
https://wisconsin.gov
https://wisconsinrailplan.gov
https://wisconsinroundabouts.gov
https://wisdoj.gov
https://wisdotplans.gov
https://wispd.gov
https://wistaysafe.gov
https://workforcetn.gov
https://wsdot.gov
https://wslb.gov
https://wv457.gov
https://wvago.gov
https://wvbold.gov
https://wvbti.gov
https://wvbvm.gov
https://wvcheckbook.gov
https://wvconsumerprotection.gov
https://wvcsi.gov
https://wvdnr.gov
https://wv.gov
https://wvhouse.gov
https://wvinsurance.gov
https://wvlegislature.gov
https://wvoasis.gov
https://wvot.gov
https://wvpresident.gov
https://wvpurchasing.gov
https://wvrevenue.gov
https://wvrtboard.gov
https://wvsao.gov
https://wvsenate.gov
https://wvseniorservices.gov
https://wvsos.gov
https://wvspeaker.gov
https://wvsp.gov
https://wvsto.gov
https://wvsurplus.gov
https://wvtax.gov
https://wvtreasury.gov
https://wvunclaimedproperty.gov
https://wycampaignfinance.gov
https://wycandidatefiling.gov
https://wy.gov
https://wyoboards.gov
https://wyocourts.gov
https://wyo.gov
https://wyoleg.gov
https://wyomingcapitol.gov
https://wyoming.gov
https://wyominglmi.gov
https://wyomingofficeoftourism.gov
https://wyomingsense.gov
https://wyopen.gov
https://wyoreg.gov
https://zerodeathsmd.gov
https://zeroinwisconsin.gov
https://capeandislandsda.gov
https://idcourts.gov
https://iowaeda.gov
https://ks.gov
https://schouse.gov
https://scsenate.gov
https://scstatehouse.gov
https://wmata.gov
https://alabamavotes.gov
https://aselectionoffice.gov
https://azcleanelections.gov
https://bringitnc.gov
https://floridaelectionwatch.gov
https://govotecolorado.gov
https://govotetn.gov
https://iavoters.gov
https://idahovotes.gov
https://mnvotes.gov
https://mtelectionresults.gov
https://myvotect.gov
https://ncsbe.gov
https://nyvotes.gov
https://oregonvotes.gov
https://registertovoteflorida.gov
https://registertovotenv.gov
https://scelectionnet.gov
https://scvotes.gov
https://sosin.gov
https://vivote.gov
https://voteidaho.gov
https://voteindiana.gov
https://votekansas.gov
https://voteohio.gov
https://votesafein.gov
https://votetexas.gov
https://votewa.gov
https://29palmsbomi-nsn.gov
https://29palmsgaming-nsn.gov
https://absenteeshawneetribe-nsn.gov
https://aguacaliente-nsn.gov
https://aguacalientetribalcourt.gov
https://aha-nsn.gov
https://ak-chin-nsn.gov
https://akiakira-nsn.gov
https://arcticvillage.gov
https://augustinepd.gov
https://augustinetribe-nsn.gov
https://badriver-nsn.gov
https://barona-nsn.gov
https://bihasitka-nsn.gov
https://bishoppaiute.gov
https://bishoppaiutetribe.gov
https://bluelakerancheria-nsn.gov
https://boisforte-nsn.gov
https://brb-nsn.gov
https://burnspaiute-nsn.gov
https://bvr-nsn.gov
https://cabazonindians-nsn.gov
https://cahtotribe-nsn.gov
https://cahuilla-nsn.gov
https://campo-nsn.gov
https://cayuganation-nsn.gov
https://cayuganationpolice.gov
https://ccthita-nsn.gov
https://cdatribe-nsn.gov
https://chehalis-nsn.gov
https://cherokee.gov
https://cherokee-nsn.gov
https://cheyenneandarapaho-nsn.gov
https://chickaloon-nsn.gov
https://chickasawartisans-nsn.gov
https://chickasaw-government-nsn.gov
https://chickasawgovernment-nsn.gov
https://chickasawjudicial-nsn.gov
https://chickasawlegislature-nsn.gov
https://chickasawnation-nsn.gov
https://chickasaw-nsn.gov
https://chickasawtribe-nsn.gov
https://chilkat-nsn.gov
https://chilkoot-nsn.gov
https://chitimacha.gov
https://chukchansihealthsafety.gov
https://chukchansi-nsn.gov
https://chumash.gov
https://cit-nsn.gov
https://cocopah.gov
https://coldspringsrancheria.gov
https://colusa-nsn.gov
https://comanchenationpolice.gov
https://cowcreek-nsn.gov
https://coyotevalley-nsn.gov
https://crhc-nsn.gov
https://critfc-nsn.gov
https://crit-nsn.gov
https://crow-nsn.gov
https://cskt.gov
https://cvmt-nsn.gov
https://delawarenation-nsn.gov
https://dineh-nsn.gov
https://dotlakevillagecouncil-nsn.gov
https://ebci.gov
https://ebci-nsn.gov
https://ebcired-nsn.gov
https://ebki-nsn.gov
https://eklutna-nsn.gov
https://elkvalley-nsn.gov
https://estoo-nsn.gov
https://eyak-nsn.gov
https://fcp-nsn.gov
https://fcpotawatomi-nsn.gov
https://fsst-nsn.gov
https://gilariver-nsn.gov
https://glt-nsn.gov
https://grandportage.gov
https://gtb-nsn.gov
https://gunlaketribe-nsn.gov
https://hannahvillepotawatomi-nsn.gov
https://havasupai-nsn.gov
https://hoopa-nsn.gov
https://hopi-nsn.gov
https://hpultribe-nsn.gov
https://hualapai-nsn.gov
https://icas-nsn.gov
https://igiugig.gov
https://iipaynation-nsn.gov
https://iipaynationofsantaysabel-nsn.gov
https://iowatribe-nsn.gov
https://isletapueblo-nsn.gov
https://jacksonrancheria-nsn.gov
https://jiv-nsn.gov
https://kaibabpaiute-nsn.gov
https://kake-nsn.gov
https://kalispeltribe-nsn.gov
https://kawaika-nsn.gov
https://kawnation.gov
https://kayentatownship-nsn.gov
https://klamathtribalhealth.gov
https://ktik-nsn.gov
https://laguna-nsn.gov
https://lagunapueblo-nsn.gov
https://lajolla-nsn.gov
https://lco-nsn.gov
https://lrboi-nsn.gov
https://ltbbodawa-nsn.gov
https://lummihealth.gov
https://lummi-nsn.gov
https://lvd-nsn.gov
https://manzanita-nsn.gov
https://mashantucketpequot-nsn.gov
https://mashpeewampanoagtribe-nsn.gov
https://mattaponi.gov
https://mbci.gov
https://mcn-nsn.gov
https://mechoopda-nsn.gov
https://menominee-nsn.gov
https://mesagrandeband-nsn.gov
https://meskwaki-nsn.gov
https://miccosukee-nsn.gov
https://micmac-nsn.gov
https://middletownrancheria-nsn.gov
https://millelacsband-nsn.gov
https://mohican-nsn.gov
https://monacannation.gov
https://mooretownrancheria-nsn.gov
https://morongo.gov
https://morongo-nsn.gov
https://mptn-nsn.gov
https://muckleshoot.gov
https://muscogeenation-nsn.gov
https://mwtribe-nsn.gov
https://nansemond.gov
https://navajo-nsn.gov
https://nciha-nsn.gov
https://nfriha-nsn.gov
https://nfr-nsn.gov
https://nhbp.gov
https://nhbp-nsn.gov
https://ninilchiktribe-nsn.gov
https://nipmuc.gov
https://nisqually-nsn.gov
https://nooksack-nsn.gov
https://northforkrancheria-nsn.gov
https://nvb-nsn.gov
https://oglala.gov
https://oneida-nsn.gov
https://osagecongress-nsn.gov
https://osagecourts-nsn.gov
https://osagenation-nsn.gov
https://ottawatribe.gov
https://pascuayaqui-nsn.gov
https://paskenta-nsn.gov
https://pauma-nsn.gov
https://pci-nsn.gov
https://pechanga-nsn.gov
https://penobscottribalhealth.gov
https://pequot-nsn.gov
https://phc-nsn.gov
https://pinoleville-nsn.gov
https://piquashawnee.gov
https://pitrivertribe.gov
https://pitu.gov
https://poarchcreekindians-nsn.gov
https://pokagonband-nsn.gov
https://pol-nsn.gov
https://ponca-nsn.gov
https://poncatribe-ne.gov
https://puliklatribe.gov
https://puyalluptribe-nsn.gov
https://qcv-nsn.gov
https://quapawnation.gov
https://qvir-nsn.gov
https://ramona-nsn.gov
https://redcliff-nsn.gov
https://reddingrancheria-nsn.gov
https://rincon-nsn.gov
https://rosebudsiouxtribe-nsn.gov
https://rrcbc-nsn.gov
https://rst-nsn.gov
https://sacandfoxnation-nsn.gov
https://samishnation.gov
https://sanjuanpaiute-nsn.gov
https://sanmanuel-nsn.gov
https://santaana-nsn.gov
https://santarosacahuilla-nsn.gov
https://santarosa-nsn.gov
https://scatdhhs.gov
https://scat-nsn.gov
https://scc-nsn.gov
https://scit-nsn.gov
https://scottsvalley-nsn.gov
https://shawnee-nsn.gov
https://shinnecock-nsn.gov
https://shoalwaterbay-nsn.gov
https://sir-nsn.gov
https://sitkatribe-nsn.gov
https://skokwellness.gov
https://sno-nsn.gov
https://soboba-nsn.gov
https://southernute-nsn.gov
https://srmt-nsn.gov
https://srpmic-nsn.gov
https://srrgc-nsn.gov
https://stcroixojibwe-nsn.gov
https://sv-nsn.gov
https://swinomish-nsn.gov
https://swo-nsn.gov
https://sycuan.gov
https://sycuan-nsn.gov
https://tachi-yokut-nsn.gov
https://tamaya.gov
https://tamaya-nsn.gov
https://taospueblo-nsn.gov
https://tbyi.gov
https://tejonindiantribe-nsn.gov
https://tlingitandhaida.gov
https://tmdci-nsn.gov
https://tojc-nsn.gov
https://tolc-nsn.gov
https://tolowa.gov
https://tolowa-nsn.gov
https://tonation-nsn.gov
https://torresmartinez-nsn.gov
https://tulalipair-nsn.gov
https://tulalip.gov
https://tulalip-nsn.gov
https://tulaliptribalcourt-nsn.gov
https://tulaliptribes-nsn.gov
https://tulerivertribe-nsn.gov
https://ukb-nsn.gov
https://umitribe.gov
https://uppersiouxcommunity-nsn.gov
https://uppersiouxpolice-nsn.gov
https://upperskagittribe-nsn.gov
https://viejas-nsn.gov
https://viejastribalcourts-nsn.gov
https://wakpamnilake-nsn.gov
https://wampanoagtribe-nsn.gov
https://warmsprings-nsn.gov
https://whiteearth-nsn.gov
https://wiltonrancheria-nsn.gov
https://wyandotte-nation-nsn.gov
https://yakamafish-nsn.gov
https://yakamanation-nsn.gov
https://ydsp-nsn.gov
https://yochadehe.gov
https://yochadehe-nsn.gov
https://ypt-nsn.gov
https://29palmstcc.gov
https://fortsillapache-nsn.gov
https://kbic-nsn.gov
https://keweenawbay-nsn.gov
https://lummiswd.gov
https://minnesotacitymn.gov
https://rockdalecountyga.gov
https://risp.gov
"""


def parse():
    parser = argparse.ArgumentParser(prog="Importer", description="Workspace Importer")

    parser.add_argument("-k", "--key")
    parser.add_argument("-f", "--file-name")
    parser.add_argument("--location", default="127.0.0.1/apps/places")
    parser.add_argument("-w", "--workspace")

    return parser, parser.parse_args()


def add_link(location, key, domain):
    url = location + "/entry-add-ext?key=" + key
    post_data = {"link": domain, "tag": ""}
    
    try:
        print("Running: {} for:{}".format(url, domain))

        response = requests.post(url=url, data=post_data, verify = False)
        
        if response.status_code != 200:
            print(f"Error: {response.status_code}")
            print(f"Response: {response.text}")
        else:
            print("OK!")
        
        return response

    except requests.exceptions.RequestException as e:
        print(f"Request failed: {e}")
        return None  # Return None if the request fails


def main():
    WebConfig.disable_ssl_warnings()

    global domain_list
    parser, args = parse()

    location = args.location

    domain_list = domain_list.split("\n")
    for domain in domain_list:
        domain = domain.strip()
        if domain != "":
            add_link(location, args.key, domain)


if __name__ == "__main__":
    main()
