"""
This is example script about how to use this project as a simple RSS reader
"""
from webtools import (
    WebConfig,
    HttpPageHandler,
    FeedClientParser,
    FeedClient,
)

from sqlalchemy import (
    create_engine,
)

# Initial sources list. Will be used to populate SQLite
sources = [
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC7shUDSkHjuQNegPhGdANQQ", "title" : "2666 - The art of listening"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCF4cAwaYlXAt2LcnqUOgtMA", "title" : "a vox in the void"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCiRiQGCHGjDLT9FQXFW0I3A", "title" : "academy of ideas"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCJhay24LTpO1s4bIZxuIqKw", "title" : "accu conference"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCnkp4xDOwqqJD7sSM3xdUiQ", "title" : "adamneely"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCUSElbgKZpE4Xdh5aFWG-Ig", "title" : "airpano vr"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCu7_D0o48KbfhpEohoP7YSQ", "title" : "andreas spiess"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCC552Sd-3nyi_tk2BudLUzA", "title" : "asap science"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCQeRaTukNYft1_6AZPACnog", "title" : "asmongold tv"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCXGgrKt94gR6lmN4aN3mYTg", "title" : "austin evans"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC2J-0g_nxlwcD9JBK1eTleQ", "title" : "auto focus"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCwUizOU8pPWXdXNniXypQEQ", "title" : "awakenwithJP"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCyl5V3-J_Bsy3x-EBCJwepg", "title" : "babylon bee"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UChHxJaKDqH4bOs0pX3hkKnA", "title" : "basically homeless"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCH4BNI0-FOK2dMXoFtViWHw", "title" : "be smart"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC3osNjJeuDdvyALIEP-nh0g", "title" : "behind the curtain"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCnQC_G5Xsjhp9fEJKuIcrSw", "title" : "ben shapiro"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCNu7GSRF7Y10OIWHQHpAx1g", "title" : "bez planu"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCmrLCXSDScliR7q8AxxjvXg", "title" : "black pidgeon speaks"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC7vVhkEfw4nOGp8TyDk7RcQ", "title" : "boston dynamics"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UClozNP-QPyVatzpGKC25s0A", "title" : "brad colbow"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCld68syR8Wi-GY_n4CaoJGA", "title" : "brodie robertson"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCxHAlbZQNFU2LgEtiqd2Maw", "title" : "c++ weekly with jason turner"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCZUyPT9DkJWmS_DzdOi7RIA", "title" : "caleb curry"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCL0QSFSUfW8cHua_rDpltTg", "title" : "call me chato"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCROQqK3_z79JuTetNP3pIXQ", "title" : "captain midnight"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCtinbF-Q-fVthA0qrFQTgXQ", "title" : "caseyneistat"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCLLO-H4NQXNa_DhUv-rqN9g", "title" : "cd action"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCPKT_csvP72boVX0XrMtagQ", "title" : "cercle"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC2C_jShtL725hvbm1arSV9w", "title" : "cgp grey"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCwjvvgGX6oby5mZ3gbDe8Ug", "title" : "china insights"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCgFP46yVT-GG4o1TgXn-04Q", "title" : "china uncensored"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCctjGdm2NlMNzIlxz02IsXA", "title" : "chris ray gun"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCg6gPGh8HU2U01vaFCAsvmQ", "title" : "christ titus tech"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCuVLG9pThvBABcYCm7pkNkA", "title" : "climate town"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCWEHue8kksIaktO8KTTN_zg", "title" : "coding entrepreneurs"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCFQMnBA3CS502aghlcr0_aw", "title" : "cofeezilla"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC4QZ_LsYcvcq7qOsOhpAX4A", "title" : "coldfusion"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCX_t3BvnQtS5IHzto_y7tbw", "title" : "coreteks"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCCsREoj8rSRkEvxWqxr74rQ", "title" : "cyber news"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC9Ntx-EF3LzKY1nQ5rTUP2g", "title" : "cyriak"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCw--xPGVVxYzRsWyV1nFqgg", "title" : "daniel greene"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCD8J_xbbBuGobmw_N5ga3MA", "title" : "denis shiryaev"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCVls1GmFKf6WlTraIb_IaJg", "title" : "distrotube"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCTSRIY3GLFYIpkR2QwyeklA", "title" : "drew gooden"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCD4EOyXKjfDUhCI6jlOZZYQ", "title" : "eli the computer guy"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCCDGVMGoT8ql8JQLJt715jA", "title" : "emzdanowicz"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCDNHPNeWScAC8h8IxtEBtkQ", "title" : "eons of battle"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC_0CVCfC_3iuHqmyClu59Uw", "title" : "eta prime"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC_DmOS_FBvO4H27U7X0OtRg", "title" : "fearless & far"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCO7fujFV_MuxTM0TuZrnE6Q", "title" : "felix colgrave"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCG_nvdTLdijiAAuPKxtvBjA", "title" : "filmento"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCsBjURrPoezykLs9EqgamOA", "title" : "fireship"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCNnKprAG-MWLsk-GsbsC2BA", "title" : "flashgitz"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCyNtlmLB73-7gtlBz00XOQQ", "title" : "folding ideas"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC2WHjPDvbE6O328n17ZGcfg", "title" : "forrest knight"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC8butISFwT-Wl7EV0hUK0BQ", "title" : "freeCodeCamp.org"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC98tcedR6gULv8_b70WJKyw", "title" : "frog leap studios"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCRG_N2uO405WO4P3Ruef9NA", "title" : "friday checkout"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC3ScyryU9Oy9Wse3a8OAmYQ", "title" : "frontline pbs | official"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCVrvnobbNGGMsS5n2mJwfOg", "title" : "fun for louis"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCkPjHTuNd_ycm__29dXM3Nw", "title" : "g f darwin"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCHDxYLv8iovIbhrfl16CNyg", "title" : "gamelinked"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCNvzD7Z-g64bPXxGzaQaa4g", "title" : "gameranx"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UChIs72whgZI9w6d6FhwGGHA", "title" : "gamers nexus"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCbu2SsF-Or3Rsn3NxqODImw", "title" : "gamespot"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCXa_bzvv7Oo1glaW9FldDhQ", "title" : "gaming bolt"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCmEbe0XH51CI09gm_9Fcn8Q", "title" : "glass reflection"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCNTqu16j3F6RbtHZI-3untg", "title" : "glink"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCbO4Vs1vlAA9hz7Ad7IMgug", "title" : "guerilla miniature games"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UClt01z1wHHT7c5lKcU8pxRQ", "title" : "hbomberguy"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCnorhjQR4zJkT7AVNhu395Q", "title" : "home renovision dyi"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCP2vaEZS8MvZrFklwBtW1GA", "title" : "home repair tutor"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCpPndhUatYo4NLn3fleQ2Fw", "title" : "hrejterzy"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCQDhxkSxZA6lxdeXE19aoRA", "title" : "hugh jeffreys"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC6x7GwJxuoABSosgVXDYtTw", "title" : "i like to make stuff"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCKWaEZ-_VweaEx1j62do_vQ", "title" : "ibm technology"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCKy1dAqELo0zrOtPkf0eTMw", "title" : "ign - YouTube"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCVg2AVe6eTCTVoWQ9AwrIHg", "title" : "in deep geek"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCcyq283he07B7_KUX07mmtA", "title" : "insider business"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCoOjH8D2XAgjzQlneM2W0EQ", "title" : "jake tran"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCHu2KNu6TtJ0p4hpSW7Yv7Q", "title" : "jazza"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCR-DXc1voovS8nhAvccRZhg", "title" : "jeff gerling"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC7v3-2K1N84V67IF-WTRG-Q", "title" : "jeremy jahns"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC-2YHgc363EdcusLIBbgxzg", "title" : "joe scott"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCVIFCOJwv3emlVmBbPCZrvw", "title" : "joel havier"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCmGSJVG3mCRXVOP4yZrU1Dw", "title" : "john harris"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCL_f53ZEJxp8TtlOkHwMV9Q", "title" : "jordan peterson"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC-91UA-Xy2Cvb98deRXuggA", "title" : "joshua fluke"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCnxGkOGNMqQEUMvroOWps6Q", "title" : "jre clips"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCy0Pr5u-MwGXXzp_GDd4m_g", "title" : "julie nolke"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC337i8LcUSM4UMbLf820I8Q", "title" : "just some guy"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCgH8NCuYcVzxxrfsrBj1u3A", "title" : "justin hawkings rides again"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UClhEl4bMD8_escGCCTmRAYg", "title" : "kanal zero"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC3I2GFN_F8WudD_2jUZbojA", "title" : "kexp"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCLRlryMfL8ffxzrtqv0_k_w", "title" : "kino check"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC3_9M27BalxsXuRyfKvPiEA", "title" : "klangphonics"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC2_KC8lshtCyiLApy27raYw", "title" : "knowledgehusk"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCG2kQBVlgG7kOigXZTcKrQw", "title" : "kolem sie toczy"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCaifrB5IrvGNPJmPeVOcqBA", "title" : "kruggsmash"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCL0WiIwugwTXU5YBFvatbNg", "title" : "ku bogu"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCLr4hMhk_2KE0GUBSBrspGA", "title" : "kuba klawiter"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCJKt_QVDyUbqdm3ag_py2eQ", "title" : "kuokka77"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCsXVk37bltHxD1rDPwtNM8Q", "title" : "kurzgesagt - in a nutshell"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCme4ZOv65uzGADXuvtHkSvA", "title" : "langusta na palmie"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UChvithwOECK5g_19TjldMKw", "title" : "laowhy86"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCtVGGeUqfVHOK4Q6nAwYO3g", "title" : "laterclips"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC3_kehZbfRz-KrjXIqeIiPw", "title" : "leadhead"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC6oHLp5r0FcXwzxmWzL1aSg", "title" : "life in the 1800s"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCs7nPQIEba0T3tGOWWsZpJQ", "title" : "like stories of old"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCyC_4jvPzLiSkJkLIkA7B8g", "title" : "lindsey stirling"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCXuqSBlHAE6Xw-yeJA0Tunw", "title" : "linus tech tips"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCz1fTbwui7o5aDZ6W1dOLTQ", "title" : "literature devil"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCFLFc8Lpbwt4jPtY1_Ai5yA", "title" : "lmg clips"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCymYq4Piq0BrhnM18aQzTlg", "title" : "lon tv"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCac6m8K3OGHUT4itHwpCAmw", "title" : "lost in time"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCl2mFZoRqjw_ELax4Yisf6w", "title" : "louis rossman"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC8RfCCzWsMgNspTI-GTFenQ", "title" : "luetin09"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCPOeoWonGJfK6wM3S8hZ0Tw", "title" : "lukhash"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCD4BKI2kgcOIi9xhqrQgbXw", "title" : "lukhash - topic"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC2eYFnH61tmytImy1mTYvhA", "title" : "luke smith"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCfDX69pxC4q6yKSaugs196g", "title" : "magia natury"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UClOGLGPOqlAiLmOvXW5lKbw", "title" : "mandalore gaming"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCKtu_JtQCY0yryIy6zK4ZCg", "title" : "marc brunet"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCOrplaGWXnDW86Zn-zonHIw", "title" : "mario budowlaniec"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCBJycsmduvYEL83R_U4JriQ", "title" : "marques brownlee"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCTTZqMWBvLsUYqYwKTdjvkw", "title" : "mateusz chrobok"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCO01ytfzgXYy4glnPJm4PPQ", "title" : "matt walsh"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCx-KWLTKlB83hDI6UKECtJQ", "title" : "max"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC91V6D3nkhP89wUb9f_h17g", "title" : "meat canyon"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC7YOGHUfC1Tb6E4pudI9STA", "title" : "mental outlaw"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCEBb1b_L6zDS3xTUrIALZOw", "title" : "mit opencourseware"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCmFeOdJI3IXgTBDzqBLD8qg", "title" : "moon"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCGMXM2RS39k1UwyNVoyzHYw", "title" : "mosak marcin"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCl5dXugC3XZeDVsDkTaWJ4g", "title" : "mountain trekker"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCX6OQ3DkcsbYNE6H8uQQuVA", "title" : "mr beast"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC5nc_ZtjKW1htCVZVRxlQAQ", "title" : "mrsuiicidesheep"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCMiJRAwDNSNzuYeN2uWa0pA", "title" : "mrwhosetheboss"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCsM-ZFKD_8vlDjfhKRNUk1A", "title" : "muzotv"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCjuKQCmKlCtrPL2wl1uIphQ", "title" : "more pegasus"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCtecHyLSXoL3P-xgFsbQh-g", "title" : "na galazi"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC1W8ShdwtfgjRHdbl1Lctcw", "title" : "nass"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCW0gH2G-cMKAEjEkI4YhnPA", "title" : "nerd of the rings"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC5T0tXJN5CrMZUEJuz4oovw", "title" : "nerdrotic"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCXjmz8dFzRJZrZY8eFiXNUQ", "title" : "nerdstalgic"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCD-4g5w1h8xQpLaNS_ghU4g", "title" : "newretrowave"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCe6nK69Yc1zna7QSJEfA9pw", "title" : "niebezpiecznik"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCura5JPb8QkzXrMfAxq4Ssw", "title" : "niekryty krytyk"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC8abMPJmTPmsaSc7j-lwIhQ", "title" : "nineteenth century videos. back to life"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC_aEa8K-EOJ3D6gOs7HcyNg", "title" : "nocopyrightsounds"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCrjKdwxaQMSV_NDywgKXVmw", "title" : "novaspirit tech"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC4eYXhJI4-7wSWc8UNRwD4A", "title" : "npr music"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCyCJi-Ht-GPakArh4ZQnVUA", "title" : "otava yo"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCittVh8imKanO_5KohzDbpg", "title" : "paul joseph watson"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCq6VFHwMzcMXbuKyG7SQYIg", "title" : "penguinz0"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC9Kq-yEt1iYsbUzNOoIRK0g", "title" : "pitch meeting"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC7kI8WjpCfFoMSNDuRh_4lA", "title" : "pitchfork"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCn-K7GIs62ENvdQe6ZZk9-w", "title" : "pogo"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCSiPjfAJBgbFlIUsxOWpK0w", "title" : "pomplamoose"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCORIeT1hk6tYBuntEXsguLg", "title" : "postmodernJukebox"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCzQUP1qoWDoEbmsQxvdjxgQ", "title" : "powerfulljre"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCQJWtTnAHhEG5w4uN0udnUQ", "title" : "prime video"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCi8C7TNs2ohrc6hnRQ5Sn2w", "title" : "programmers are also human"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCL9PlYkRD3Q-RZca6CCnPKw", "title" : "project veritas"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCGHDQtN_vzFYJaq_Fx1eikg", "title" : "qxir"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UChnxLLvzviaR5NeKOevB8iQ", "title" : "red means recording"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCOAS2LRJ9VzWrblDtVljaUA", "title" : "retrodemoscene"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCYVU6rModlGxvJbszCclGGw", "title" : "rob braxman tech"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCqqY6fzyLY3OmdjYRe2eJAg", "title" : "roosevelt"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCi8e0iOVk1fEOogdfu4YgfA", "title" : "rotten tomatoes trailers"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCswH8ovgUp5Bdg-0_JTYFNw", "title" : "russel brand"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCh9IfI45mmk59eDvSWtuuhQ", "title" : "ryan george"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCzKFvBRI6VT3jYJq6a820nA", "title" : "ryan long"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCA3-nIYWu4PTWkb6NwhEpzg", "title" : "ryan reynolds"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCyseFvMP4mZVlU5iEEbAamA", "title" : "salvatore ganacci"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCd6vEDS3SOhWbXZrxbrf_bw", "title" : "samtime"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC-2JUs_G21BrJ0efehwGkUw", "title" : "scary pockets"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCWTA5Yd0rAkQt5-9etIFoBA", "title" : "scifun"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCZYTClx2T1of7BRZ86-8fow", "title" : "scishow"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCOpcACMWblDls9Z6GERVi1A", "title" : "screen junkies"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCl7mAGnY4jh4Ps8rhhh8XZg", "title" : "serpentza"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCyRhIGDUKdIOw07Pd8pHxCw", "title" : "shut up and sit down"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCO2x-p9gg9TLKneXlibGR7w", "title" : "snazzy labs"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCEq_Dr1GHvnNPQNfgOzhZ8Q", "title" : "solid jj"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCtMVHI3AJD4Qk4hcbZnI9ZQ", "title" : "someordinarygamers"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC9lKBRxxsDIarUmNaPe0h0Q", "title" : "sorelle amore finance"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCDvZTWvHZPTxJ4K1yTD2a1g", "title" : "squidmar miniatures"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCD6VugMZKRhSyzWEWA9W2fg", "title" : "sssethtzeentach"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCSFy-1JrpZf0tFlRZfo-Rvw", "title" : "sydney watson"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC2CKTY1TXQ4YQ3AHvyCgtbQ", "title" : "tabletop miniatures"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCtZO3K2p8mqFwiKWb9k7fXA", "title" : "techaltar"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCjSEJkpGbcZhvo0lr-44X_w", "title" : "techhut"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCeeFfhMcJa1kjtfZAGskOCA", "title" : "techlinked"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCs6KfncB4OV6Vug4o_bzijg", "title" : "techlore"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCy0tKL1T7wFoYcxCe0xjN6Q", "title" : "technology connections"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC0vBXGSyV14uvJ4hECDOl0Q", "title" : "techquickie"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC6n8I1UDTKP1IWjQMg6_TwA", "title" : "the b1m"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCQ-W1KE9EYfdxhL6S4twUNw", "title" : "the cherno"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCI9DUIgtRGHNH_HmSTcfUbA", "title" : "the closer look"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCSJPFQdZwrOutnmSFYtbstA", "title" : "the critical drinker"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCAKcSON6PSG_JkTbXh2WdIg", "title" : "the current"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCDVb4m_5QHhZElT47E1oODg", "title" : "the dave cullen show"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCqg5FCR7NrpvlBWMXdt-5Vg", "title" : "the escapist"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC3sznuotAs2ohg_U__Jzj_Q", "title" : "the film theorists"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCjr2bPAyPV7t35MvcgT3W8Q", "title" : "the hated one"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC5UAwBUum7CPN5buc-_N1Fw", "title" : "the linux experiment"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCmKurapML4BF9Bjtj4RbvXw", "title" : "the piano guys"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCJdKr0Bgd_5saZYqLCa9mng", "title" : "the rubin report"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC7IcJI8PUf5Z3zKxnZvTBog", "title" : "the school of life"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCMMBpWfWUd3xlcOxrot_neA", "title" : "the virtual reality show"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCK7tptUDHh-RYDsdxO1-5QQ", "title" : "the wall street journal"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCJbPGzawDH1njbqV-D5HqKw", "title" : "thenewboston"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCQSpnDG3YsFNf5-qHocF-WQ", "title" : "thiojoe"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCRlICXvO4XR4HMeEB9JjDlA", "title" : "thoughty2"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCSbdMXOI_3HGiFviLZO6kNA", "title" : "thrillseeker"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCW7AGm8JSBEEew61dJIgl_A", "title" : "tom cardy"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCxt2r57cLastdmrReiQJkEg", "title" : "tom nicolas"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCBa659QWEk1AI4Tg--mrJ2A", "title" : "tom scott"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCj5Ug7sV0Id9g-NEfFa1psg", "title" : "tomasz samolyk"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC3Y_HaUqzTYABL2whcwGOKA", "title" : "tyler fisher"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCjtUS7-SZTi6pXjUbzGHQCg", "title" : "undecided with matt farrell"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCj5Ug7sV0Id9g-NEfFa1psg", "title" : "up is not down"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCwSv086EAByBY-Z7y-QR_cQ", "title" : "uszi"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC_7PqixGIdE-jjoHKMPYpGA", "title" : "uwaga naukowy belkot"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCa1WbVCkTqd5ecG6G2adIow", "title" : "vagabrothers"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCHnyfMqiRRG1u-2MsSQLbXA", "title" : "veritasium"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC_kH5ltlZdtFAY2qV_lp2xA", "title" : "vince vintage"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCsmk8NDVMct75j_Bfb9Ah7w", "title" : "virtual reality oasis"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCLsnJt_eyqkGZ4ZEM__xCOg", "title" : "vlog casha"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC6AXBF-78lNa3_TjAIWZWmQ", "title" : "vr gorilla"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC6nSFpj9HTCZ5t-N3Rm3-HA", "title" : "vsauce"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCwdh3MTrFq3sXlB4ct8B-Fg", "title" : "warhammer"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UC9RM-iSvTu1uPJb8X5yp3EQ", "title" : "wendover productions"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCvg_4SPPEZ7y4pk_iB7z6sw", "title" : "whimsu"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCcXhhVwCT6_WqjkEniejRJQ", "title" : "wintergatan"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCxXu9tCU63mF1ntk89XPkzA", "title" : "worthkids"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCMOgdURr7d8pOVlc-alkfRg", "title" : "xKito music"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCcefcZRL2oaA_uBNeo5UOWg", "title" : "Y combinator"},
        {"url" : "https://www.youtube.com/feeds/videos.xml?channel_id=UCIw5fgJcTtR2Av-0JkZp-xg", "title" : "Yuri wong"},

        # Reddit
        {"url" : "https://www.reddit.com/r/3Dprinting/.rss", "title" : "Reddit - 3D Printing"},
        {"url" : "https://www.reddit.com/r/Warhammer/.rss", "title" : "Reddit - Warhammer"},
        {"url" : "https://www.reddit.com/r/amiga/.rss", "title" : "Reddit - Amiga"},
        {"url" : "https://www.reddit.com/r/boardgames/.rss", "title" : "Reddit - BoardGames"},
        {"url" : "https://www.reddit.com/r/emulation/.rss", "title" : "Reddit - Emulation"},
        {"url" : "https://www.reddit.com/r/selfhosted/.rss", "title" : "Reddit - Self-Hosted"},
        {"url" : "https://www.reddit.com/r/RISCV/.rss", "title" : "Reddit - RISC-V"},
        {"url" : "https://www.reddit.com/r/webscraping/.rss", "title" : "Reddit - WebScraping"},
        {"url" : "https://www.reddit.com/r/programming/.rss", "title" : "Reddit - Programming"},
        {"url" : "https://www.reddit.com/r/raspberry_pi/.rss", "title" : "Reddit - Raspberry PI"},
        {"url" : "https://www.reddit.com/.rss", "title" : "Reddit - Front page"},
        {"url" : "https://www.reddit.com/r/news/.rss", "title" : "Reddit - News"},
        {"url" : "https://www.reddit.com/r/politics/.rss", "title" : "Reddit - Politics"},
        {"url" : "https://www.reddit.com/r/worldnews/.rss", "title" : "Reddit - World News"},
        {"url" : "https://www.reddit.com/r/ReverseEngineering/.rss", "title" : "Reddit - ReverseEngineering"},
        {"url" : "https://www.reddit.com/r/Warhammer40k/.rss", "title" : "Reddit - Warhammer40k"},
        {"url" : "https://www.reddit.com/r/searchengines/.rss", "title" : "Reddit - Search Engines"},

        # Google news have RSS feeds https://www.google.com/intl/en_US/news_feed_terms.html
        {"url" : "https://news.google.com/news?ned=en_US&topic=h&output=rss", "title" : "Google News - Top stories"},
        {"url" : "https://news.google.com/news?ned=en_US&topic=w&output=rss", "title" : "Google News - World"},
        {"url" : "https://news.google.com/news?ned=en_US&topic=t&output=rss", "title" : "Google News - Tech"},

        # other
        {"url" : "https://hnrss.org/frontpage", "title" : "Hacker News Front Page"},
        {"url" : "https://warhammer-community.com/feed", "title" : "Warhammer community"},
]


def main():

    parser = FeedClientParser()
    parser.parse()

    engine = create_engine("sqlite:///feedclient.db")

    p = FeedClient(sources = sources, day_limit=7, engine=engine, parser=parser)

    if p.parser.args.verbose:
        WebConfig.use_print_logging()

    # scraping server is not running, we do not use port
    HttpPageHandler.crawling_server_port = 0
    HttpPageHandler.crawling_full_script = None
    HttpPageHandler.crawling_headless_script = None

    HttpPageHandler.crawling_full_script = "poetry run python crawleebeautifulsoup.py"
    HttpPageHandler.crawling_headless_script = "poetry run python crawleebeautifulsoup.py"

    p.run()

main()
