from django.urls import path
from django.urls import include
from django.contrib.auth import views as auth
from django.views.generic import RedirectView
from django.views.generic.base import TemplateView

from . import views
from .apps import LinkDatabase
from .viewspkg import (
    viewentries,
    viewsources,
    viewcustom,
    viewuseractions,
    viewcomments,
    viewsystem,
    viewexport,
    viewdomains,
)

# register app namespace
# TODO https://stackoverflow.com/questions/30494000/django-url-namespaces-the-template-has-to-know-its-namespace
app_name = str(LinkDatabase.name)

# fmt: off
urlpatterns = [
    path("", views.index, name="index"),
    # sources
    path("sources/", viewsources.SourceListView.as_view(), name="sources"),
    path("source/<int:pk>/", viewsources.SourceDetailView.as_view(), name="source-detail"),
    path("source-json/<int:pk>", viewsources.source_json, name="source-json"),
    path("sources-json/", viewsources.sources_json, name="sources-json"),
    path("source-add", viewsources.add_source, name="source-add"),
    path("source-add-simple", viewsources.add_source_simple, name="source-add-simple"),
    path("source-remove/<int:pk>/", viewsources.remove_source, name="source-remove"),
    path("source-remove-entries/<int:pk>/", viewsources.source_remove_entries, name="source-remove-entries"),
    path("source-edit/<int:pk>/", viewsources.edit_source, name="source-edit"),
    path("source-refresh/<int:pk>/", viewsources.refresh_source, name="source-refresh"),
    path("source-save/<int:pk>/", viewsources.wayback_save, name="source-save"),
    path("source-import-yt-links/<int:pk>/", viewsources.import_youtube_links_for_source, name="source-import-yt-links"),
    path("source-process-text/<int:pk>/", viewsources.process_source_text, name="source-process-text"),
    path("source-fix-entries/<int:source_pk>/", viewsources.source_fix_entries, name="source-fix-entries",),
    path("sources-remove-all/", viewsources.remove_all_sources, name="sources-remove-all"),
    path("sources-enable-all/", viewsources.enable_all_sources, name="sources-enable-all"),
    path("sources-disable-all/", viewsources.disable_all_sources, name="sources-disable-all"),
    path("sources-manual-refresh/", viewsources.sources_manual_refresh, name="sources-manual-refresh"),
    # entries
    path("entries/", viewentries.EntriesSearchListView.as_view(), name="entries"),
    path("entries-recent/", viewentries.EntriesRecentListView.as_view(), name="entries-recent"),
    path("entries-archived/", viewentries.EntriesArchiveListView.as_view(), name="entries-archived"),
    path("entries-untagged/", viewentries.EntriesNotTaggedView.as_view(), name="entries-untagged"),
    path("entries-bookmarked/", viewentries.EntriesBookmarkedListView.as_view(), name="entries-bookmarked"),
    path("entries-json/", viewentries.entries_json, name="entries-json"),
    path("entries-omni-search-init", viewentries.entries_omni_search_init, name="entries-omni-search-init"),
    path("entries-search-init", viewentries.entries_search_init, name="entries-search-init"),
    path("entries-archived-init", viewentries.entries_archived_init, name="entries-archived-init"),
    path("entries-bookmarked-init", viewentries.entries_bookmarked_init, name="entries-bookmarked-init"),
    path("entries-recent-init", viewentries.entries_recent_init, name="entries-recent-init"),
    path("entries-omni-search", viewentries.EntriesOmniListView.as_view(), name="entries-omni-search"),
    path("entries-remove-all", viewentries.entries_remove_all, name="entries-remove-all"),
    path("entries-remove-nonbookmarked", viewentries.entries_remove_nonbookmarked, name="entries-remove-nonbookmarked"),
    path("entry/<int:pk>/", viewentries.EntryDetailView.as_view(), name="entry-detail"),
    path("entry-json/<int:pk>/", viewentries.entry_json, name="entry-json"),
    path("entry-archived/<int:pk>/", viewentries.EntryArchivedDetailView.as_view(), name="entry-archived"),
    path("entry-add", viewentries.add_entry, name="entry-add"),
    path("entry-reset-data/<int:pk>/", viewentries.entry_reset_data, name="entry-reset-data"),
    path("entry-update-data/<int:pk>/", viewentries.entry_update_data, name="entry-update-data"),
    path("entry-add-simple", viewentries.add_simple_entry, name="entry-add-simple"),
    path("entry-edit/<int:pk>/", viewentries.edit_entry, name="entry-edit"),
    path("entry-remove/<int:pk>/", viewentries.remove_entry, name="entry-remove"),
    path("entry-dead/<int:pk>/", viewentries.entry_dead, name="entry-dead"),
    path("entry-not-dead/<int:pk>/", viewentries.entry_not_dead, name="entry-not-dead"),
    path("entry-bookmark/<int:pk>/", viewentries.make_bookmarked_entry, name="entry-bookmark"),
    path("entry-notbookmark/<int:pk>/", viewentries.make_not_bookmarked_entry, name="entry-notbookmark"),
    path("entry-download-music/<int:pk>/", viewcustom.download_music, name="entry-download-music",),
    path("entry-download-video/<int:pk>/", viewcustom.download_video, name="entry-download-video",),
    path("entry-download/<int:pk>/", viewentries.download_entry, name="entry-download"),
    path("entry-archive-edit/<int:pk>/", viewentries.archive_edit_entry, name="entry-archive-edit"),
    path("entry-archive-bookmark/<int:pk>/", viewentries.archive_make_bookmarked_entry, name="entry-archive-bookmark"),
    path("entry-archive-notbookmark/<int:pk>/", viewentries.archive_make_not_bookmarked_entry, name="entry-archive-notbookmark"),
    path("entry-archive-hide/<int:pk>/", viewentries.archive_hide_entry, name="entry-archive-hide"),
    path("entry-archive-remove/<int:pk>/", viewentries.archive_remove_entry, name="entry-archive-remove"),
    path("entries-archive-remove-all", viewentries.archive_entries_remove_all, name="entries-archive-remove-all"),
    path("entry-save/<int:pk>/", viewentries.wayback_save, name="entry-save"),
    # tags
    path("entry-tag/<int:pk>/", viewuseractions.tag_entry, name="entry-tag"),
    path("tag-remove/<int:pk>/", viewuseractions.tag_remove, name="tag-remove"),
    path("tag-remove-str/<str:tag>/", viewuseractions.tag_remove_str, name="tag-remove-str"),
    path("tag-remove-form/", viewuseractions.tag_remove_form, name="tag-remove-form"),
    path("tags-entry-remove/<int:entrypk>/", viewuseractions.tags_entry_remove, name="tags-entry-remove",),
    path("tags-entry-show/<int:entrypk>/", viewuseractions.tags_entry_show, name="tags-entry-show",),
    path("tag-rename", viewuseractions.tag_rename, name="tag-rename"),
    path("tags-show-all", viewuseractions.AllTags.as_view(), name="tags-show-all"),
    path("tags-show-recent", viewuseractions.RecentTags.as_view(), name="tags-show-recent"),
    path("tags-many", viewuseractions.tag_many, name="tag-many"),
    # comment
    path("entry-comment-add/<int:link_id>", viewcomments.entry_add_comment, name="entry-comment-add",),
    path("entry-comment-edit/<int:pk>/", viewcomments.entry_comment_edit, name="entry-comment-edit",),
    path("entry-comment-remove/<int:pk>/", viewcomments.entry_comment_remove, name="entry-comment-remove",),
    # vote
    path("entry-vote/<int:pk>/", viewuseractions.entry_vote, name="entry-vote"),
    # admin views
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path("admin-page/", viewsystem.admin_page, name="admin-page"),
    path("user-config", viewsystem.user_config, name="user-config"),
    path("configuration/", viewsystem.configuration_page, name="configuration"),
    path("system-status/", viewsystem.system_status, name="system-status"),
    path("about/", viewsystem.about, name="about"),
    path("missing-rights/", viewsystem.missing_rights, name="missing-rights"),
    path("show-info/", viewcustom.show_info, name="show-info"),
    path("reset-config/", viewsystem.reset_config, name="reset-config"),
    # background jobs
    path("backgroundjobs/", viewsystem.BackgroundJobsView.as_view(), name="backgroundjobs",),
    path("backgroundjob-add", viewsystem.backgroundjob_add, name="backgroundjob-add",),
    path("backgroundjob-prio-up/<int:pk>/", viewsystem.backgroundjob_prio_up, name="backgroundjob-prio-up",),
    path("backgroundjob-prio-down/<int:pk>/", viewsystem.backgroundjob_prio_down, name="backgroundjob-prio-down",),
    path("backgroundjob-enable/<int:pk>/", viewsystem.backgroundjob_enable, name="backgroundjob-enable",),
    path("backgroundjob-disable/<int:pk>/", viewsystem.backgroundjob_disable, name="backgroundjob-disable",),
    path("backgroundjobs-check-new/", viewsystem.backgroundjobs_check_new, name="backgroundjobs-check-new",),
    path("backgroundjobs-perform-all/", viewsystem.backgroundjobs_perform_all, name="backgroundjobs-perform-all",),
    path("backgroundjob-remove/<int:pk>/", viewsystem.backgroundjob_remove, name="backgroundjob-remove",),
    path("backgroundjobs-remove/<str:job_type>/", viewsystem.backgroundjobs_remove, name="backgroundjobs-remove",),
    path("backgroundjobs-remove-all/", viewsystem.backgroundjobs_remove_all, name="backgroundjobs-remove-all",),
    # persistant infos
    path("logs/", viewsystem.AppLoggingView.as_view(), name="logs",),
    path("truncate-log", viewsystem.truncate_log, name="truncate-log"),
    path("truncate-log-errors", viewsystem.truncate_log_errors, name="truncate-log-errors"),
    path("truncate-log-all", viewsystem.truncate_log_all, name="truncate-log-all"),
    # import / export
    path("data-export-add", viewexport.data_export_add, name="data-export-add"),
    path("data-export-edit/<int:pk>/", viewexport.data_export_edit, name="data-export-edit"),
    path("data-export-remove/<int:pk>/", viewexport.data_export_remove, name="data-export-remove"),
    path("data-exports/", viewexport.DataExportListView.as_view(), name="data-exports",),
    path("data-export/<int:pk>/", viewexport.DataExportDetailsView.as_view(), name="data-export",),
    path("write-bookmarks", viewexport.write_bookmarks, name="write-bookmarks"),
    path("write-daily-data-form", viewexport.write_daily_data_form, name="write-daily-data-form",),
    path("write-tag-form", viewexport.write_tag_form, name="write-tag-form"),
    path("push-daily-data-form", viewexport.push_daily_data_form, name="push-daily-data-form"),
    path("import-bookmarks", viewexport.import_bookmarks, name="import-bookmarks"),
    path("import-daily-data", viewexport.import_daily_data, name="import-daily-data"),
    path("import-sources", viewexport.import_sources, name="import-sources"),
    path("import-reading-list", viewexport.import_reading_list_view, name="import-reading-list",),
    path("import-from-instance", viewexport.import_from_instance, name="import-from-instance",),
    path("import-from-files", viewexport.import_from_files, name="import-from-files",),
    path("import-source-ia/<int:pk>/", viewexport.import_source_from_ia, name="import-source-ia",),
    # domains
    path("domains/", viewdomains.DomainsListView.as_view(), name="domains",),
    path("domain/<int:pk>/", viewdomains.DomainsDetailView.as_view(), name="domain-detail",),
    path("domain-by-name/", viewdomains.DomainsByNameDetailView.as_view(), name="domain-by-name",),
    path("domain-edit/<int:pk>/", viewdomains.domain_edit, name="domain-edit",),
    path("domain-update-data/<int:pk>/", viewdomains.domain_update_data, name="domain-update-data",),
    path("domain-json/<int:pk>/", viewdomains.domain_json, name="domain-json",),
    path("domain-remove/<int:pk>/", viewdomains.domain_remove, name="domain-remove",),
    path("domains-fix/", viewdomains.domains_fix, name="domains-fix",),
    path("domains-read-bookmarks/", viewdomains.domains_read_bookmarks, name="domains-read-bookmarks",),
    path("domains-json/", viewdomains.domains_json, name="domains-json"),
    path("domains-category-list/", viewdomains.domains_category_list, name="domains-category-list"),
    path("domains-reset-dynamic-data/", viewdomains.domains_reset_dynamic_data, name="domains-reset-dynamic-data"),
    path("domains-remove-all/", viewdomains.domains_remove_all, name="domains-remove-all",),
    # keywords
    path("keywords/", viewcustom.keywords, name="keywords",),
    path("keyword-remove", viewcustom.keyword_remove, name="keyword-remove",),
    path("keywords-remove-all/", viewcustom.keywords_remove_all, name="keywords-remove-all",),
    # other, debug forms
    path("page-show-props", viewcustom.page_show_properties, name="page-show-props",),
    path("page-scan-input", viewcustom.page_scan_input, name="page-scan-input",),
    path("page-scan-contents", viewcustom.page_scan_contents, name="page-scan-contents",),
    path("page-scan", viewcustom.page_scan, name="page-scan",),

    path("check-move-archive", viewcustom.check_if_move_to_archive, name="check-move-archive",),
    path("data-errors", viewcustom.data_errors_page, name="data-errors"),
    path("fix-entry-tags/<int:entrypk>/", viewcustom.fix_entry_tags, name="fix-entry-tags",),
    path("test-page", viewcustom.test_page, name="test-page"),
    path("test-form-page", viewcustom.test_form_page, name="test-form-page"),
    path("fix-bookmarked-yt", viewcustom.fix_bookmarked_yt, name="fix-bookmarked-yt"),
    # login
    path("accounts/", include("django.contrib.auth.urls")),
    path("rsshistory/accounts/logout/", RedirectView.as_view(url="rsshistory/")),
    path("accounts/logout/", RedirectView.as_view(url="rsshistory/")),
]
# fmt: on
