"""
Django settings for linklibrary project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import base64
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

SECRET_KEY = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
FERNET_KEY=base64.urlsafe_b64encode(b"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Add necessary hosts here
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

DB_DB = os.environ["DB_DB"]
DB_USER = os.environ["DB_USER"]
DB_PASSWORD = os.environ["DB_PASSWORD"]

RABBIT_SERVER=os.environ["RABBIT_SERVER"]
MEMCACHED_SERVER=os.environ["MEMCACHED_SERVER"]
MEMCACHED_PORT=os.environ["MEMCACHED_PORT"]
DB_SERVER=os.environ["DB_SERVER"]
#CELERY_BROKER_URL = f'amqp://guest:guest@{RABBIT_SERVER}'


if "CRAWLER_BUDDY_SERVER" in os.environ:
    CRAWLER_BUDDY_SERVER = os.environ["CRAWLER_BUDDY_SERVER"]
else:
    CRAWLER_BUDDY_SERVER = None

if "CRAWLER_BUDDY_PORT" in os.environ:
    CRAWLER_BUDDY_PORT = os.environ["CRAWLER_BUDDY_PORT"]
else:
    CRAWLER_BUDDY_PORT = None

if CRAWLER_BUDDY_SERVER and CRAWLER_BUDDY_PORT:
    CRAWLER_BUDDY_URL = CRAWLER_BUDDY_SERVER + ":" + str(CRAWLER_BUDDY_PORT)
else:
    CRAWLER_BUDDY_URL = None

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Manual edit start
    "rsshistory.apps.LinkDatabase",
]

# to make auth system to work
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'linklibrary.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'linklibrary.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_TZ = True
TIME_ZONE = 'UTC'
USE_I18N = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
