github_json = """{
  "id": 531848052,
  "node_id": "R_kgDOH7NbdA",
  "name": "Django-link-archive",
  "full_name": "rumca-js/Django-link-archive",
  "private": false,
  "owner": {
    "login": "rumca-js",
    "id": 653884,
    "node_id": "MDQ6VXNlcjY1Mzg4NA==",
    "avatar_url": "https://avatars.githubusercontent.com/u/653884?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rumca-js",
    "html_url": "https://github.com/rumca-js",
    "followers_url": "https://api.github.com/users/rumca-js/followers",
    "following_url": "https://api.github.com/users/rumca-js/following{/other_user}",
    "gists_url": "https://api.github.com/users/rumca-js/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rumca-js/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rumca-js/subscriptions",
    "organizations_url": "https://api.github.com/users/rumca-js/orgs",
    "repos_url": "https://api.github.com/users/rumca-js/repos",
    "events_url": "https://api.github.com/users/rumca-js/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rumca-js/received_events",
    "type": "User",
    "user_view_type": "public",
    "site_admin": false
  },
  "html_url": "https://github.com/rumca-js/Django-link-archive",
  "description": "Self-hostable link database",
  "fork": false,
  "url": "https://api.github.com/repos/rumca-js/Django-link-archive",
  "forks_url": "https://api.github.com/repos/rumca-js/Django-link-archive/forks",
  "keys_url": "https://api.github.com/repos/rumca-js/Django-link-archive/keys{/key_id}",
  "collaborators_url": "https://api.github.com/repos/rumca-js/Django-link-archive/collaborators{/collaborator}",
  "teams_url": "https://api.github.com/repos/rumca-js/Django-link-archive/teams",
  "hooks_url": "https://api.github.com/repos/rumca-js/Django-link-archive/hooks",
  "issue_events_url": "https://api.github.com/repos/rumca-js/Django-link-archive/issues/events{/number}",
  "events_url": "https://api.github.com/repos/rumca-js/Django-link-archive/events",
  "assignees_url": "https://api.github.com/repos/rumca-js/Django-link-archive/assignees{/user}",
  "branches_url": "https://api.github.com/repos/rumca-js/Django-link-archive/branches{/branch}",
  "tags_url": "https://api.github.com/repos/rumca-js/Django-link-archive/tags",
  "blobs_url": "https://api.github.com/repos/rumca-js/Django-link-archive/git/blobs{/sha}",
  "git_tags_url": "https://api.github.com/repos/rumca-js/Django-link-archive/git/tags{/sha}",
  "git_refs_url": "https://api.github.com/repos/rumca-js/Django-link-archive/git/refs{/sha}",
  "trees_url": "https://api.github.com/repos/rumca-js/Django-link-archive/git/trees{/sha}",
  "statuses_url": "https://api.github.com/repos/rumca-js/Django-link-archive/statuses/{sha}",
  "languages_url": "https://api.github.com/repos/rumca-js/Django-link-archive/languages",
  "stargazers_url": "https://api.github.com/repos/rumca-js/Django-link-archive/stargazers",
  "contributors_url": "https://api.github.com/repos/rumca-js/Django-link-archive/contributors",
  "subscribers_url": "https://api.github.com/repos/rumca-js/Django-link-archive/subscribers",
  "subscription_url": "https://api.github.com/repos/rumca-js/Django-link-archive/subscription",
  "commits_url": "https://api.github.com/repos/rumca-js/Django-link-archive/commits{/sha}",
  "git_commits_url": "https://api.github.com/repos/rumca-js/Django-link-archive/git/commits{/sha}",
  "comments_url": "https://api.github.com/repos/rumca-js/Django-link-archive/comments{/number}",
  "issue_comment_url": "https://api.github.com/repos/rumca-js/Django-link-archive/issues/comments{/number}",
  "contents_url": "https://api.github.com/repos/rumca-js/Django-link-archive/contents/{+path}",
  "compare_url": "https://api.github.com/repos/rumca-js/Django-link-archive/compare/{base}...{head}",
  "merges_url": "https://api.github.com/repos/rumca-js/Django-link-archive/merges",
  "archive_url": "https://api.github.com/repos/rumca-js/Django-link-archive/{archive_format}{/ref}",
  "downloads_url": "https://api.github.com/repos/rumca-js/Django-link-archive/downloads",
  "issues_url": "https://api.github.com/repos/rumca-js/Django-link-archive/issues{/number}",
  "pulls_url": "https://api.github.com/repos/rumca-js/Django-link-archive/pulls{/number}",
  "milestones_url": "https://api.github.com/repos/rumca-js/Django-link-archive/milestones{/number}",
  "notifications_url": "https://api.github.com/repos/rumca-js/Django-link-archive/notifications{?since,all,participating}",
  "labels_url": "https://api.github.com/repos/rumca-js/Django-link-archive/labels{/name}",
  "releases_url": "https://api.github.com/repos/rumca-js/Django-link-archive/releases{/id}",
  "deployments_url": "https://api.github.com/repos/rumca-js/Django-link-archive/deployments",
  "created_at": "2022-09-02T08:42:47Z",
  "updated_at": "2025-01-07T16:15:08Z",
  "pushed_at": "2025-01-07T16:15:03Z",
  "git_url": "git://github.com/rumca-js/Django-link-archive.git",
  "ssh_url": "git@github.com:rumca-js/Django-link-archive.git",
  "clone_url": "https://github.com/rumca-js/Django-link-archive.git",
  "svn_url": "https://github.com/rumca-js/Django-link-archive",
  "homepage": "https://rumca-js.github.io/quickstart/public/static_lists/viewerzip.html",
  "size": 33361,
  "stargazers_count": 75,
  "watchers_count": 75,
  "language": "Python",
  "has_issues": true,
  "has_projects": true,
  "has_downloads": true,
  "has_wiki": true,
  "has_pages": false,
  "has_discussions": false,
  "forks_count": 4,
  "mirror_url": null,
  "archived": false,
  "disabled": false,
  "open_issues_count": 127,
  "license": {
    "key": "gpl-3.0",
    "name": "GNU General Public License v3.0",
    "spdx_id": "GPL-3.0",
    "url": "https://api.github.com/licenses/gpl-3.0",
    "node_id": "MDc6TGljZW5zZTk="
  },
  "allow_forking": true,
  "is_template": false,
  "web_commit_signoff_required": false,
  "topics": [
    "bookmark-manager",
    "dead-internet",
    "link-aggregation",
    "link-aggregator",
    "link-archive",
    "link-database",
    "reddit-alternative",
    "rss",
    "rss-archive",
    "rss-client",
    "rss-feed",
    "rss-reader",
    "rssfeed",
    "search-engine",
    "youtube-client",
    "youtube-filter"
  ],
  "visibility": "public",
  "forks": 4,
  "open_issues": 127,
  "watchers": 75,
  "default_branch": "main",
  "temp_clone_token": null,
  "network_count": 4,
  "subscribers_count": 4
}
"""
