warhammer_community_rss = """
<html><head><meta name="color-scheme" content="light dark"></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">&lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
	&gt;

&lt;channel&gt;
	&lt;title&gt;Warhammer Community&lt;/title&gt;
	&lt;atom:link href="https://www.warhammer-community.com/en-us/feed/" rel="self" type="application/rss+xml" /&gt;
	&lt;link&gt;https://www.warhammer-community.com/en-us/&lt;/link&gt;
	&lt;description&gt;The home of Warhammer on the web.&lt;/description&gt;
	&lt;lastBuildDate&gt;Mon, 07 Jun 2021 17:03:03 +0000&lt;/lastBuildDate&gt;
	&lt;language&gt;en-GB&lt;/language&gt;
	&lt;sy:updatePeriod&gt;
	hourly	&lt;/sy:updatePeriod&gt;
	&lt;sy:updateFrequency&gt;
	1	&lt;/sy:updateFrequency&gt;
	&lt;generator&gt;https://wordpress.org/?v=6.5.5&lt;/generator&gt;

&lt;image&gt;
	&lt;url&gt;https://www.warhammer-community.com/wp-content/uploads/2017/09/cropped-web-icon-32x32.png&lt;/url&gt;
	&lt;title&gt;Warhammer Community&lt;/title&gt;
	&lt;link&gt;https://www.warhammer-community.com/en-us/&lt;/link&gt;
	&lt;width&gt;32&lt;/width&gt;
	&lt;height&gt;32&lt;/height&gt;
&lt;/image&gt; 
	&lt;item&gt;
		&lt;title&gt;The Opening Bonanza for the Warhammer Store &amp;#038; Cafe in Los Angeles Starts This Saturday&lt;/title&gt;
		&lt;link&gt;https://www.warhammer-community.com/en-us/2021/06/07/the-opening-bonanza-for-the-warhammer-store-cafe-in-los-angeles-starts-this-saturday/&lt;/link&gt;
		
		&lt;dc:creator&gt;&lt;![CDATA[Daniel Billiald]]&gt;&lt;/dc:creator&gt;
		&lt;pubDate&gt;Mon, 07 Jun 2021 17:20:14 +0000&lt;/pubDate&gt;
				&lt;category&gt;&lt;![CDATA[All News]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Warhammer AoS]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Warhammer 40k]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Warhammer Cafe]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Store News]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Warhammer Age of Sigmar]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Warhammer 40000]]&gt;&lt;/category&gt;
		&lt;guid isPermaLink="false"&gt;https://www.warhammer-community.com/?p=172424&lt;/guid&gt;

					&lt;description&gt;&lt;![CDATA[&lt;p&gt;Get the details on the two-week opening celebration, including the exclusive swag on offer. &lt;/p&gt;
&lt;p&gt;The post &lt;a href="https://www.warhammer-community.com/en-us/2021/06/07/the-opening-bonanza-for-the-warhammer-store-cafe-in-los-angeles-starts-this-saturday/"&gt;The Opening Bonanza for the Warhammer Store &amp;#038; Cafe in Los Angeles Starts This Saturday&lt;/a&gt; appeared first on &lt;a href="https://www.warhammer-community.com/en-us/"&gt;Warhammer Community&lt;/a&gt;.&lt;/p&gt;
]]&gt;&lt;/description&gt;
										&lt;content:encoded&gt;&lt;![CDATA[&lt;p&gt;&lt;img fetchpriority="high" decoding="async" class="aligncenter size-full wp-image-172480" src="https://www.warhammer-community.com/wp-content/uploads/2021/06/Pq760ywsL1TRZELu.jpg" alt="WHCafe LA Jun07 Header22u" width="1000" height="588" srcset="https://www.warhammer-community.com/wp-content/uploads/2021/06/Pq760ywsL1TRZELu.jpg 1000w, https://www.warhammer-community.com/wp-content/uploads/2021/06/Pq760ywsL1TRZELu-500x294.jpg 500w, https://www.warhammer-community.com/wp-content/uploads/2021/06/Pq760ywsL1TRZELu-384x226.jpg 384w, https://www.warhammer-community.com/wp-content/uploads/2021/06/Pq760ywsL1TRZELu-846x497.jpg 846w, https://www.warhammer-community.com/wp-content/uploads/2021/06/Pq760ywsL1TRZELu-665x391.jpg 665w, https://www.warhammer-community.com/wp-content/uploads/2021/06/Pq760ywsL1TRZELu-490x288.jpg 490w, https://www.warhammer-community.com/wp-content/uploads/2021/06/Pq760ywsL1TRZELu-330x194.jpg 330w" sizes="(max-width: 1000px) 100vw, 1000px" /&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;Look alive, West-Coast Warhammer fans. The brand new Warhammer Store &amp;amp; Cafe – LA is opening up this weekend, kicking off two weeks of awesome activities, with exclusive goodies up for grabs too. If you’re not already planning a visit, you’ll want to by the time you’re done reading this.&nbsp;&lt;/span&gt;&lt;/p&gt;
&lt;h3&gt;&lt;b&gt;When and Where&lt;/b&gt;&lt;/h3&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;The shop is located in Monrovia, CA, in the greater Los Angeles area. The doors will open up at &lt;/span&gt;&lt;b&gt;10am on Saturday, the 12th of June&lt;/b&gt;&lt;span style="font-weight: 400;"&gt;. Be there, or be square –&nbsp;and jealous of all the folks having a blast without you.&nbsp;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;img decoding="async" class="aligncenter size-full wp-image-172453" src="https://www.warhammer-community.com/wp-content/uploads/2021/06/VNsoaORjyB4XEYlf.jpg" alt="WHCafe LA Jun07 Date" width="1000" height="1000" srcset="https://www.warhammer-community.com/wp-content/uploads/2021/06/VNsoaORjyB4XEYlf.jpg 1000w, https://www.warhammer-community.com/wp-content/uploads/2021/06/VNsoaORjyB4XEYlf-500x500.jpg 500w, https://www.warhammer-community.com/wp-content/uploads/2021/06/VNsoaORjyB4XEYlf-320x320.jpg 320w, https://www.warhammer-community.com/wp-content/uploads/2021/06/VNsoaORjyB4XEYlf-226x226.jpg 226w, https://www.warhammer-community.com/wp-content/uploads/2021/06/VNsoaORjyB4XEYlf-846x846.jpg 846w, https://www.warhammer-community.com/wp-content/uploads/2021/06/VNsoaORjyB4XEYlf-665x665.jpg 665w, https://www.warhammer-community.com/wp-content/uploads/2021/06/VNsoaORjyB4XEYlf-490x490.jpg 490w, https://www.warhammer-community.com/wp-content/uploads/2021/06/VNsoaORjyB4XEYlf-330x330.jpg 330w" sizes="(max-width: 1000px) 100vw, 1000px" /&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;We expect some crowds, but the store team will make sure everyone is safe and entertained with fun games, trivia, and activities while you wait in line. It will all be worth it when you see what’s inside…&nbsp;&lt;/span&gt;&lt;/p&gt;
&lt;h3&gt;&lt;b&gt;Shop For Exclusive Items, Forge World Resin, and More&lt;/b&gt;&lt;/h3&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;Not only are the shelves loaded with Citadel models and boxed games, but the Warhammer Store &amp;amp; Cafe also carries loads of Black Library books, plus a wide range of resin miniatures from Forge World.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;In case you missed the &lt;a href="https://www.warhammer-community.com/en-us/2021/04/29/the-warhammer-store-cafe-in-la-is-celebrating-its-grand-opening/"&gt;initial announcement&lt;/a&gt;, you’ll have the chance to buy hard-to-find models like Berek the Indomitable and Leena Stormspire for Warhammer Age of Sigmar, plus &lt;/span&gt;&lt;span style="font-weight: 400;"&gt;Ripper Jackson and Sergeant Jovan for Warhammer 40,000.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;img decoding="async" class="aligncenter size-full wp-image-172426" src="https://www.warhammer-community.com/wp-content/uploads/2021/06/hAmwstjEJ7HvnBb3.jpg" alt="WHCafe LA Jun07 Content1n" width="1000" height="624" srcset="https://www.warhammer-community.com/wp-content/uploads/2021/06/hAmwstjEJ7HvnBb3.jpg 1000w, https://www.warhammer-community.com/wp-content/uploads/2021/06/hAmwstjEJ7HvnBb3-500x312.jpg 500w, https://www.warhammer-community.com/wp-content/uploads/2021/06/hAmwstjEJ7HvnBb3-362x226.jpg 362w, https://www.warhammer-community.com/wp-content/uploads/2021/06/hAmwstjEJ7HvnBb3-846x528.jpg 846w, https://www.warhammer-community.com/wp-content/uploads/2021/06/hAmwstjEJ7HvnBb3-665x415.jpg 665w, https://www.warhammer-community.com/wp-content/uploads/2021/06/hAmwstjEJ7HvnBb3-490x306.jpg 490w, https://www.warhammer-community.com/wp-content/uploads/2021/06/hAmwstjEJ7HvnBb3-330x206.jpg 330w" sizes="(max-width: 1000px) 100vw, 1000px" /&gt;&lt;/p&gt;
&lt;p&gt;&lt;img loading="lazy" decoding="async" class="aligncenter size-full wp-image-172435" src="https://www.warhammer-community.com/wp-content/uploads/2021/06/6tLKX42ChOvl7oHm.jpg" alt="WHCafe LA Jun07 Content2p" width="1000" height="624" srcset="https://www.warhammer-community.com/wp-content/uploads/2021/06/6tLKX42ChOvl7oHm.jpg 1000w, https://www.warhammer-community.com/wp-content/uploads/2021/06/6tLKX42ChOvl7oHm-500x312.jpg 500w, https://www.warhammer-community.com/wp-content/uploads/2021/06/6tLKX42ChOvl7oHm-362x226.jpg 362w, https://www.warhammer-community.com/wp-content/uploads/2021/06/6tLKX42ChOvl7oHm-846x528.jpg 846w, https://www.warhammer-community.com/wp-content/uploads/2021/06/6tLKX42ChOvl7oHm-665x415.jpg 665w, https://www.warhammer-community.com/wp-content/uploads/2021/06/6tLKX42ChOvl7oHm-490x306.jpg 490w, https://www.warhammer-community.com/wp-content/uploads/2021/06/6tLKX42ChOvl7oHm-330x206.jpg 330w" sizes="(max-width: 1000px) 100vw, 1000px" /&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;In addition to these four, they’ll have a very limited stock of two event-exclusive models –&nbsp;Holga Clovenhorn, Aspiring Champion of Chaos, and Necron Lord Hasmoteph the Resplendent.&nbsp;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;img loading="lazy" decoding="async" class="aligncenter size-full wp-image-164595" src="https://www.warhammer-community.com/wp-content/uploads/2021/05/md17EkhmhcaRavRy.jpg" alt="" width="1000" height="1000" srcset="https://www.warhammer-community.com/wp-content/uploads/2021/05/md17EkhmhcaRavRy.jpg 1000w, https://www.warhammer-community.com/wp-content/uploads/2021/05/md17EkhmhcaRavRy-500x500.jpg 500w, https://www.warhammer-community.com/wp-content/uploads/2021/05/md17EkhmhcaRavRy-320x320.jpg 320w, https://www.warhammer-community.com/wp-content/uploads/2021/05/md17EkhmhcaRavRy-226x226.jpg 226w, https://www.warhammer-community.com/wp-content/uploads/2021/05/md17EkhmhcaRavRy-846x846.jpg 846w, https://www.warhammer-community.com/wp-content/uploads/2021/05/md17EkhmhcaRavRy-665x665.jpg 665w, https://www.warhammer-community.com/wp-content/uploads/2021/05/md17EkhmhcaRavRy-490x490.jpg 490w, https://www.warhammer-community.com/wp-content/uploads/2021/05/md17EkhmhcaRavRy-330x330.jpg 330w" sizes="(max-width: 1000px) 100vw, 1000px" /&gt;&lt;/p&gt;
&lt;p&gt;&lt;img loading="lazy" decoding="async" class="aligncenter size-full wp-image-164586" src="https://www.warhammer-community.com/wp-content/uploads/2021/05/GgrNkBicuT3FymPa.jpg" alt="" width="1000" height="1000" srcset="https://www.warhammer-community.com/wp-content/uploads/2021/05/GgrNkBicuT3FymPa.jpg 1000w, https://www.warhammer-community.com/wp-content/uploads/2021/05/GgrNkBicuT3FymPa-500x500.jpg 500w, https://www.warhammer-community.com/wp-content/uploads/2021/05/GgrNkBicuT3FymPa-320x320.jpg 320w, https://www.warhammer-community.com/wp-content/uploads/2021/05/GgrNkBicuT3FymPa-226x226.jpg 226w, https://www.warhammer-community.com/wp-content/uploads/2021/05/GgrNkBicuT3FymPa-846x846.jpg 846w, https://www.warhammer-community.com/wp-content/uploads/2021/05/GgrNkBicuT3FymPa-665x665.jpg 665w, https://www.warhammer-community.com/wp-content/uploads/2021/05/GgrNkBicuT3FymPa-490x490.jpg 490w, https://www.warhammer-community.com/wp-content/uploads/2021/05/GgrNkBicuT3FymPa-330x330.jpg 330w" sizes="(max-width: 1000px) 100vw, 1000px" /&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;You can also pick up a set of these handsome black-and-gold Store Founding Dice to remember the occasion.&nbsp;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;&lt;img loading="lazy" decoding="async" class="aligncenter size-full wp-image-172444" src="https://www.warhammer-community.com/wp-content/uploads/2021/06/FH8pYA4qSgsgITuq.jpg" alt="WHCafe LA Jun07 Content3m" width="1000" height="1000" srcset="https://www.warhammer-community.com/wp-content/uploads/2021/06/FH8pYA4qSgsgITuq.jpg 1000w, https://www.warhammer-community.com/wp-content/uploads/2021/06/FH8pYA4qSgsgITuq-500x500.jpg 500w, https://www.warhammer-community.com/wp-content/uploads/2021/06/FH8pYA4qSgsgITuq-320x320.jpg 320w, https://www.warhammer-community.com/wp-content/uploads/2021/06/FH8pYA4qSgsgITuq-226x226.jpg 226w, https://www.warhammer-community.com/wp-content/uploads/2021/06/FH8pYA4qSgsgITuq-846x846.jpg 846w, https://www.warhammer-community.com/wp-content/uploads/2021/06/FH8pYA4qSgsgITuq-665x665.jpg 665w, https://www.warhammer-community.com/wp-content/uploads/2021/06/FH8pYA4qSgsgITuq-490x490.jpg 490w, https://www.warhammer-community.com/wp-content/uploads/2021/06/FH8pYA4qSgsgITuq-330x330.jpg 330w" sizes="(max-width: 1000px) 100vw, 1000px" /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;In addition to all that, you can shop for a range of fun Warhammer collectibles from Half Moon Bay, including items like pin badges, drinking cups, and so forth. This stock will vary, so stop by often to take a look at what’s available.&nbsp;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;img loading="lazy" decoding="async" class="aligncenter size-full wp-image-172471" src="https://www.warhammer-community.com/wp-content/uploads/2021/06/O21xeLnf0CkiSU1W.jpg" alt="WHCafe LA Jun07 HalfMoonBay1onkv" width="1000" height="1085" srcset="https://www.warhammer-community.com/wp-content/uploads/2021/06/O21xeLnf0CkiSU1W.jpg 1000w, https://www.warhammer-community.com/wp-content/uploads/2021/06/O21xeLnf0CkiSU1W-461x500.jpg 461w, https://www.warhammer-community.com/wp-content/uploads/2021/06/O21xeLnf0CkiSU1W-944x1024.jpg 944w, https://www.warhammer-community.com/wp-content/uploads/2021/06/O21xeLnf0CkiSU1W-208x226.jpg 208w, https://www.warhammer-community.com/wp-content/uploads/2021/06/O21xeLnf0CkiSU1W-846x918.jpg 846w, https://www.warhammer-community.com/wp-content/uploads/2021/06/O21xeLnf0CkiSU1W-665x722.jpg 665w, https://www.warhammer-community.com/wp-content/uploads/2021/06/O21xeLnf0CkiSU1W-490x532.jpg 490w, https://www.warhammer-community.com/wp-content/uploads/2021/06/O21xeLnf0CkiSU1W-330x358.jpg 330w" sizes="(max-width: 1000px) 100vw, 1000px" /&gt;&lt;/p&gt;
&lt;h3&gt;&lt;b&gt;Grab Loads of Swag&nbsp;&lt;/b&gt;&lt;/h3&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;Naturally, the two-week opening celebration will include some promotional items with qualifying purchases. Stock is limited, so if you’re after things like satchels, accessory bags, art books, t-shirts, and more, make the trip as early as possible to avoid missing out.&nbsp;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;Follow the &lt;/span&gt;&lt;a href="https://www.facebook.com/WHStoreandCafeLosAngeles/" target="_blank" rel="noopener"&gt;&lt;span style="font-weight: 400;"&gt;Warhammer Store &amp;amp; Cafe – LA on Facebook&lt;/span&gt;&lt;/a&gt;&lt;span style="font-weight: 400;"&gt; for more updates, and feel free to shoot a message to the staff if you have any questions or concerns. We’re looking forward to an exciting launch, and we can’t wait to meet you all.&nbsp;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;The post &lt;a href="https://www.warhammer-community.com/en-us/2021/06/07/the-opening-bonanza-for-the-warhammer-store-cafe-in-los-angeles-starts-this-saturday/"&gt;The Opening Bonanza for the Warhammer Store &amp;#038; Cafe in Los Angeles Starts This Saturday&lt;/a&gt; appeared first on &lt;a href="https://www.warhammer-community.com/en-us/"&gt;Warhammer Community&lt;/a&gt;.&lt;/p&gt;
]]&gt;&lt;/content:encoded&gt;
					
		
		
		            &lt;image&gt;https://www.warhammer-community.com/wp-content/uploads/2021/06/KnFBbKDBkpDd1zjK.jpg&lt;/image&gt;
            &lt;image_thumbnail&gt;https://www.warhammer-community.com/wp-content/uploads/2021/06/KnFBbKDBkpDd1zjK-320x320.jpg&lt;/image_thumbnail&gt;
            &lt;image_medium&gt;https://www.warhammer-community.com/wp-content/uploads/2021/06/KnFBbKDBkpDd1zjK-500x310.jpg&lt;/image_medium&gt;
            &lt;image_large&gt;https://www.warhammer-community.com/wp-content/uploads/2021/06/KnFBbKDBkpDd1zjK.jpg&lt;/image_large&gt;
        	&lt;/item&gt;
		&lt;item&gt;
		&lt;title&gt;The Warhammer Store &amp;#038; Cafe in LA Is Celebrating Its Grand Opening&lt;/title&gt;
		&lt;link&gt;https://www.warhammer-community.com/en-us/2021/04/29/the-warhammer-store-cafe-in-la-is-celebrating-its-grand-opening/&lt;/link&gt;
		
		&lt;dc:creator&gt;&lt;![CDATA[Daniel Billiald]]&gt;&lt;/dc:creator&gt;
		&lt;pubDate&gt;Thu, 29 Apr 2021 12:55:01 +0000&lt;/pubDate&gt;
				&lt;category&gt;&lt;![CDATA[All News]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Los Angeles]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Warhammer AoS]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Warhammer 40k]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Store News]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Warhammer Age of Sigmar]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Warhammer 40000]]&gt;&lt;/category&gt;
		&lt;guid isPermaLink="false"&gt;https://www.warhammer-community.com/?p=147940&lt;/guid&gt;

					&lt;description&gt;&lt;![CDATA[&lt;p&gt;West Coast Warhammer enthusiasts have a new destination for hobby goodies, gaming, grub, and more.&lt;/p&gt;
&lt;p&gt;The post &lt;a href="https://www.warhammer-community.com/en-us/2021/04/29/the-warhammer-store-cafe-in-la-is-celebrating-its-grand-opening/"&gt;The Warhammer Store &amp;#038; Cafe in LA Is Celebrating Its Grand Opening&lt;/a&gt; appeared first on &lt;a href="https://www.warhammer-community.com/en-us/"&gt;Warhammer Community&lt;/a&gt;.&lt;/p&gt;
]]&gt;&lt;/description&gt;
										&lt;content:encoded&gt;&lt;![CDATA[&lt;p&gt;&lt;img loading="lazy" decoding="async" class="aligncenter size-full wp-image-147987" src="https://www.warhammer-community.com/wp-content/uploads/2021/04/elftydJEc5vn6TDv.jpg" alt="WHCafe LA Apr29 Header22u" width="1000" height="588" srcset="https://www.warhammer-community.com/wp-content/uploads/2021/04/elftydJEc5vn6TDv.jpg 1000w, https://www.warhammer-community.com/wp-content/uploads/2021/04/elftydJEc5vn6TDv-500x294.jpg 500w, https://www.warhammer-community.com/wp-content/uploads/2021/04/elftydJEc5vn6TDv-384x226.jpg 384w, https://www.warhammer-community.com/wp-content/uploads/2021/04/elftydJEc5vn6TDv-846x497.jpg 846w, https://www.warhammer-community.com/wp-content/uploads/2021/04/elftydJEc5vn6TDv-665x391.jpg 665w, https://www.warhammer-community.com/wp-content/uploads/2021/04/elftydJEc5vn6TDv-490x288.jpg 490w, https://www.warhammer-community.com/wp-content/uploads/2021/04/elftydJEc5vn6TDv-330x194.jpg 330w" sizes="(max-width: 1000px) 100vw, 1000px" /&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;The Los Angeles area is about to get a whole lot more Warhammer, in the form of a brand new destination store and cafe.&nbsp;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;Mark your calendars to join the team for two weeks of celebrations – starting on the 12th of June – including the opportunity to get your hands on hard-to-find models and swag.&nbsp;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;img loading="lazy" decoding="async" class="aligncenter size-full wp-image-147969" src="https://www.warhammer-community.com/wp-content/uploads/2021/04/QWnUDIz5g7OcVpAN.jpg" alt="WHCafe LA Apr29 Date" width="1000" height="1000" srcset="https://www.warhammer-community.com/wp-content/uploads/2021/04/QWnUDIz5g7OcVpAN.jpg 1000w, https://www.warhammer-community.com/wp-content/uploads/2021/04/QWnUDIz5g7OcVpAN-500x500.jpg 500w, https://www.warhammer-community.com/wp-content/uploads/2021/04/QWnUDIz5g7OcVpAN-320x320.jpg 320w, https://www.warhammer-community.com/wp-content/uploads/2021/04/QWnUDIz5g7OcVpAN-226x226.jpg 226w, https://www.warhammer-community.com/wp-content/uploads/2021/04/QWnUDIz5g7OcVpAN-846x846.jpg 846w, https://www.warhammer-community.com/wp-content/uploads/2021/04/QWnUDIz5g7OcVpAN-665x665.jpg 665w, https://www.warhammer-community.com/wp-content/uploads/2021/04/QWnUDIz5g7OcVpAN-490x490.jpg 490w, https://www.warhammer-community.com/wp-content/uploads/2021/04/QWnUDIz5g7OcVpAN-330x330.jpg 330w" sizes="(max-width: 1000px) 100vw, 1000px" /&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;Among other goodies, you can pick up a few items that can only be found at new store openings, like Ripper Jackson, Berek the Indomitable, Leena Stormspire, and Sergeant Jovan, plus a set of commemorative dice.&nbsp;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;img loading="lazy" decoding="async" class="aligncenter size-full wp-image-147942" src="https://www.warhammer-community.com/wp-content/uploads/2021/04/WyXJEwFiqDh8thw1.jpg" alt="WHCafe LA Apr29 Content1n" width="1000" height="624" srcset="https://www.warhammer-community.com/wp-content/uploads/2021/04/WyXJEwFiqDh8thw1.jpg 1000w, https://www.warhammer-community.com/wp-content/uploads/2021/04/WyXJEwFiqDh8thw1-500x312.jpg 500w, https://www.warhammer-community.com/wp-content/uploads/2021/04/WyXJEwFiqDh8thw1-362x226.jpg 362w, https://www.warhammer-community.com/wp-content/uploads/2021/04/WyXJEwFiqDh8thw1-846x528.jpg 846w, https://www.warhammer-community.com/wp-content/uploads/2021/04/WyXJEwFiqDh8thw1-665x415.jpg 665w, https://www.warhammer-community.com/wp-content/uploads/2021/04/WyXJEwFiqDh8thw1-490x306.jpg 490w, https://www.warhammer-community.com/wp-content/uploads/2021/04/WyXJEwFiqDh8thw1-330x206.jpg 330w" sizes="(max-width: 1000px) 100vw, 1000px" /&gt;&lt;/p&gt;
&lt;p&gt;&lt;img loading="lazy" decoding="async" class="aligncenter size-full wp-image-147951" src="https://www.warhammer-community.com/wp-content/uploads/2021/04/ZBANMPTE8cl1l0b0.jpg" alt="WHCafe LA Apr29 Content2p" width="1000" height="624" srcset="https://www.warhammer-community.com/wp-content/uploads/2021/04/ZBANMPTE8cl1l0b0.jpg 1000w, https://www.warhammer-community.com/wp-content/uploads/2021/04/ZBANMPTE8cl1l0b0-500x312.jpg 500w, https://www.warhammer-community.com/wp-content/uploads/2021/04/ZBANMPTE8cl1l0b0-362x226.jpg 362w, https://www.warhammer-community.com/wp-content/uploads/2021/04/ZBANMPTE8cl1l0b0-846x528.jpg 846w, https://www.warhammer-community.com/wp-content/uploads/2021/04/ZBANMPTE8cl1l0b0-665x415.jpg 665w, https://www.warhammer-community.com/wp-content/uploads/2021/04/ZBANMPTE8cl1l0b0-490x306.jpg 490w, https://www.warhammer-community.com/wp-content/uploads/2021/04/ZBANMPTE8cl1l0b0-330x206.jpg 330w" sizes="(max-width: 1000px) 100vw, 1000px" /&gt;&lt;/p&gt;
&lt;p&gt;&lt;img loading="lazy" decoding="async" class="aligncenter size-full wp-image-147960" src="https://www.warhammer-community.com/wp-content/uploads/2021/04/qWFXAPXfV1M6gTYv.jpg" alt="WHCafe LA Apr29 Content3m" width="1000" height="1000" srcset="https://www.warhammer-community.com/wp-content/uploads/2021/04/qWFXAPXfV1M6gTYv.jpg 1000w, https://www.warhammer-community.com/wp-content/uploads/2021/04/qWFXAPXfV1M6gTYv-500x500.jpg 500w, https://www.warhammer-community.com/wp-content/uploads/2021/04/qWFXAPXfV1M6gTYv-320x320.jpg 320w, https://www.warhammer-community.com/wp-content/uploads/2021/04/qWFXAPXfV1M6gTYv-226x226.jpg 226w, https://www.warhammer-community.com/wp-content/uploads/2021/04/qWFXAPXfV1M6gTYv-846x846.jpg 846w, https://www.warhammer-community.com/wp-content/uploads/2021/04/qWFXAPXfV1M6gTYv-665x665.jpg 665w, https://www.warhammer-community.com/wp-content/uploads/2021/04/qWFXAPXfV1M6gTYv-490x490.jpg 490w, https://www.warhammer-community.com/wp-content/uploads/2021/04/qWFXAPXfV1M6gTYv-330x330.jpg 330w" sizes="(max-width: 1000px) 100vw, 1000px" /&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;We want everyone to be safe and have a good time, so the store will follow all the safety protocols you’ve come to expect: masks for everyone, keeping socially distanced, and limiting the number of folks who are in the store at one time.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;The crew is hard at work on the finishing touches, but it’s shaping up to be an amazing experience. Immerse yourself in every aspect of the hobby with a wide range of models (including Forge World miniatures) and books, an area for gaming, and a cafe to fuel you with delicious treats.&nbsp;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;Thinking about making a trip? Check out the &lt;/span&gt;&lt;a href="https://www.facebook.com/WHStoreandCafeLosAngeles/?utm_source=WarhammerCommunity&amp;amp;utm_medium=Post&amp;amp;utm_campaign=WarhammerStoreandCafeLA29042021&amp;amp;utm_content=WarhammerStoreandCafeLA29042021" target="_blank" rel="noopener"&gt;&lt;span style="font-weight: 400;"&gt;Warhammer Store &amp;amp; Cafe &amp;#8211; Los Angeles Facebook page&lt;/span&gt;&lt;/a&gt;&lt;span style="font-weight: 400;"&gt; to make plans and ask the staff any questions you may have. &lt;/span&gt;&lt;/p&gt;
&lt;p&gt;The post &lt;a href="https://www.warhammer-community.com/en-us/2021/04/29/the-warhammer-store-cafe-in-la-is-celebrating-its-grand-opening/"&gt;The Warhammer Store &amp;#038; Cafe in LA Is Celebrating Its Grand Opening&lt;/a&gt; appeared first on &lt;a href="https://www.warhammer-community.com/en-us/"&gt;Warhammer Community&lt;/a&gt;.&lt;/p&gt;
]]&gt;&lt;/content:encoded&gt;
					
		
		
		            &lt;image&gt;https://www.warhammer-community.com/wp-content/uploads/2021/04/6WRhTrGlBtLftf0L.jpg&lt;/image&gt;
            &lt;image_thumbnail&gt;https://www.warhammer-community.com/wp-content/uploads/2021/04/6WRhTrGlBtLftf0L-320x320.jpg&lt;/image_thumbnail&gt;
            &lt;image_medium&gt;https://www.warhammer-community.com/wp-content/uploads/2021/04/6WRhTrGlBtLftf0L-500x310.jpg&lt;/image_medium&gt;
            &lt;image_large&gt;https://www.warhammer-community.com/wp-content/uploads/2021/04/6WRhTrGlBtLftf0L.jpg&lt;/image_large&gt;
        	&lt;/item&gt;
		&lt;item&gt;
		&lt;title&gt;How extreme weather is affecting our North American deliveries&lt;/title&gt;
		&lt;link&gt;https://www.warhammer-community.com/en-us/2021/02/17/how-extreme-weather-is-affecting-our-north-american-deliveries/&lt;/link&gt;
		
		&lt;dc:creator&gt;&lt;![CDATA[Daniel Billiald]]&gt;&lt;/dc:creator&gt;
		&lt;pubDate&gt;Wed, 17 Feb 2021 18:16:25 +0000&lt;/pubDate&gt;
				&lt;category&gt;&lt;![CDATA[All News]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[North America]]&gt;&lt;/category&gt;
		&lt;guid isPermaLink="false"&gt;https://www.warhammer-community.com/?p=125681&lt;/guid&gt;

					&lt;description&gt;&lt;![CDATA[&lt;p&gt;Heavy snow and ice have closed our US warehouse. Read on to find out what that means for your orders.&lt;/p&gt;
&lt;p&gt;The post &lt;a href="https://www.warhammer-community.com/en-us/2021/02/17/how-extreme-weather-is-affecting-our-north-american-deliveries/"&gt;How extreme weather is affecting our North American deliveries&lt;/a&gt; appeared first on &lt;a href="https://www.warhammer-community.com/en-us/"&gt;Warhammer Community&lt;/a&gt;.&lt;/p&gt;
]]&gt;&lt;/description&gt;
										&lt;content:encoded&gt;&lt;![CDATA[&lt;p&gt;&lt;span style="font-weight: 400;"&gt;Warhammer hobbyists in North America will undoubtedly be aware that a cold-weather front has engulfed much of the US right now, with heavy snows and biting cold temperatures. While Games Workshop is a UK-based company, our North American warehouse is based in Memphis, Tennessee, and right now it’s under a blanket of snow…&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;img loading="lazy" decoding="async" class="aligncenter size-full wp-image-125683" src="https://www.warhammer-community.com/wp-content/uploads/2021/02/MepKc3wunEwOI3AG.jpg" alt="Article" width="1500" height="1000" srcset="https://www.warhammer-community.com/wp-content/uploads/2021/02/MepKc3wunEwOI3AG.jpg 1500w, https://www.warhammer-community.com/wp-content/uploads/2021/02/MepKc3wunEwOI3AG-500x333.jpg 500w, https://www.warhammer-community.com/wp-content/uploads/2021/02/MepKc3wunEwOI3AG-1024x683.jpg 1024w, https://www.warhammer-community.com/wp-content/uploads/2021/02/MepKc3wunEwOI3AG-339x226.jpg 339w, https://www.warhammer-community.com/wp-content/uploads/2021/02/MepKc3wunEwOI3AG-1060x707.jpg 1060w, https://www.warhammer-community.com/wp-content/uploads/2021/02/MepKc3wunEwOI3AG-1025x683.jpg 1025w, https://www.warhammer-community.com/wp-content/uploads/2021/02/MepKc3wunEwOI3AG-846x564.jpg 846w, https://www.warhammer-community.com/wp-content/uploads/2021/02/MepKc3wunEwOI3AG-665x443.jpg 665w, https://www.warhammer-community.com/wp-content/uploads/2021/02/MepKc3wunEwOI3AG-490x327.jpg 490w, https://www.warhammer-community.com/wp-content/uploads/2021/02/MepKc3wunEwOI3AG-330x220.jpg 330w" sizes="(max-width: 1500px) 100vw, 1500px" /&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;For now, all our colleagues are safe and well, but as a safety precaution (and, quite frankly, as a practical consideration) we’ve temporarily closed our North American warehouse.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;Unfortunately for our customers in the US and Canada, this means that, if you’ve already placed an order with us that hasn’t yet been dispatched, there will be an additional delay (we reckon about a week, but we’re all at the mercy of the snow-gods). You can continue to place orders via our online store as normal, but please be aware any new orders will also take longer to reach you.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;You might also find that Warhammer stock in your local Warhammer store or independent retailer is replaced at a slower rate than usual. Please be patient with your friendly store staff, we’ll get the stores all resupplied as soon as it’s safe to do so.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;Everyone here at Games Workshop is really sorry for any inconvenience or disappointment this causes – we hope you understand why we’re taking these steps.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;In the meantime, please stay safe, stay warm, and look after each other! &lt;/span&gt;&lt;/p&gt;
&lt;p&gt;The post &lt;a href="https://www.warhammer-community.com/en-us/2021/02/17/how-extreme-weather-is-affecting-our-north-american-deliveries/"&gt;How extreme weather is affecting our North American deliveries&lt;/a&gt; appeared first on &lt;a href="https://www.warhammer-community.com/en-us/"&gt;Warhammer Community&lt;/a&gt;.&lt;/p&gt;
]]&gt;&lt;/content:encoded&gt;
					
		
		
		            &lt;image&gt;https://www.warhammer-community.com/wp-content/uploads/2021/02/aTZz0aJpie7Bg4Tv.jpg&lt;/image&gt;
            &lt;image_thumbnail&gt;https://www.warhammer-community.com/wp-content/uploads/2021/02/aTZz0aJpie7Bg4Tv-320x320.jpg&lt;/image_thumbnail&gt;
            &lt;image_medium&gt;https://www.warhammer-community.com/wp-content/uploads/2021/02/aTZz0aJpie7Bg4Tv-500x310.jpg&lt;/image_medium&gt;
            &lt;image_large&gt;https://www.warhammer-community.com/wp-content/uploads/2021/02/aTZz0aJpie7Bg4Tv.jpg&lt;/image_large&gt;
        	&lt;/item&gt;
		&lt;item&gt;
		&lt;title&gt;Introducing the Warhammer Store &amp;#038; Cafe: Los Angeles&lt;/title&gt;
		&lt;link&gt;https://www.warhammer-community.com/en-us/2021/02/01/introducing-the-warhammer-store-cafe-los-angeles-2/&lt;/link&gt;
		
		&lt;dc:creator&gt;&lt;![CDATA[Mike Idris]]&gt;&lt;/dc:creator&gt;
		&lt;pubDate&gt;Mon, 01 Feb 2021 16:30:20 +0000&lt;/pubDate&gt;
				&lt;category&gt;&lt;![CDATA[All News]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Uncategorized @en-us]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[San Gabriel Valley]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Games]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Black Library]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Warhammer Cafe]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Texas]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Warhammer Citadel]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Hobby]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[New Store]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Monrovia]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Models]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Covid 19]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Merchandise]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Los Angeles]]&gt;&lt;/category&gt;
		&lt;guid isPermaLink="false"&gt;https://www.warhammer-community.com/?p=120754&lt;/guid&gt;

					&lt;description&gt;&lt;![CDATA[&lt;p&gt;A new Warhammer Store &amp;#038; Cafe is coming to southern California – get all details right here.&lt;/p&gt;
&lt;p&gt;The post &lt;a href="https://www.warhammer-community.com/en-us/2021/02/01/introducing-the-warhammer-store-cafe-los-angeles-2/"&gt;Introducing the Warhammer Store &amp;#038; Cafe: Los Angeles&lt;/a&gt; appeared first on &lt;a href="https://www.warhammer-community.com/en-us/"&gt;Warhammer Community&lt;/a&gt;.&lt;/p&gt;
]]&gt;&lt;/description&gt;
										&lt;content:encoded&gt;&lt;![CDATA[&lt;p&gt;&lt;img loading="lazy" decoding="async" class="aligncenter size-full wp-image-120577" src="https://www.warhammer-community.com/wp-content/uploads/2021/02/wTOjUOEsYwArPrzs.jpg" alt="WHCitadel LA Feb01 Header23bftd" width="1000" height="525" srcset="https://www.warhammer-community.com/wp-content/uploads/2021/02/wTOjUOEsYwArPrzs.jpg 1000w, https://www.warhammer-community.com/wp-content/uploads/2021/02/wTOjUOEsYwArPrzs-500x263.jpg 500w, https://www.warhammer-community.com/wp-content/uploads/2021/02/wTOjUOEsYwArPrzs-430x226.jpg 430w, https://www.warhammer-community.com/wp-content/uploads/2021/02/wTOjUOEsYwArPrzs-846x444.jpg 846w, https://www.warhammer-community.com/wp-content/uploads/2021/02/wTOjUOEsYwArPrzs-665x349.jpg 665w, https://www.warhammer-community.com/wp-content/uploads/2021/02/wTOjUOEsYwArPrzs-490x257.jpg 490w, https://www.warhammer-community.com/wp-content/uploads/2021/02/wTOjUOEsYwArPrzs-330x173.jpg 330w" sizes="(max-width: 1000px) 100vw, 1000px" /&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;Warhammer fans in southern California, rejoice – you’ll soon have a new place to enjoy your favourite hobby. We’re delighted to announce that the Warhammer Store &amp;amp; Cafe: Los Angeles is coming to the area. The exact opening date is yet to be confirmed, but we couldn’t wait to tell you about it.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;This new shop is based on the popular Warhammer Citadel in Grapevine, Texas. Just like its successor, the new LA location offers everything you love about a local Warhammer store and much, much more.&lt;/span&gt;&lt;/p&gt;
&lt;div id="attachment_120640" style="width: 510px" class="wp-caption aligncenter"&gt;&lt;img loading="lazy" decoding="async" aria-describedby="caption-attachment-120640" class="wp-image-120640 size-medium" src="https://www.warhammer-community.com/wp-content/uploads/2021/02/VzmJtK8eCo5EfKdK-500x250.jpg" alt="WHCitadel LA Oct14 Content6a" width="500" height="250" srcset="https://www.warhammer-community.com/wp-content/uploads/2021/02/VzmJtK8eCo5EfKdK-500x250.jpg 500w, https://www.warhammer-community.com/wp-content/uploads/2021/02/VzmJtK8eCo5EfKdK-452x226.jpg 452w, https://www.warhammer-community.com/wp-content/uploads/2021/02/VzmJtK8eCo5EfKdK-846x423.jpg 846w, https://www.warhammer-community.com/wp-content/uploads/2021/02/VzmJtK8eCo5EfKdK-665x333.jpg 665w, https://www.warhammer-community.com/wp-content/uploads/2021/02/VzmJtK8eCo5EfKdK-490x245.jpg 490w, https://www.warhammer-community.com/wp-content/uploads/2021/02/VzmJtK8eCo5EfKdK-330x165.jpg 330w, https://www.warhammer-community.com/wp-content/uploads/2021/02/VzmJtK8eCo5EfKdK.jpg 1000w" sizes="(max-width: 500px) 100vw, 500px" /&gt;&lt;p id="caption-attachment-120640" class="wp-caption-text"&gt;The new location makes its home in Monrovia, a beautiful and bustling shopping and cultural district.&lt;/p&gt;&lt;/div&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Games and models&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;As well as the same amazing boxed games, rulebooks, and models you’d find in other stores, the Warhammer Store &amp;amp; Cafe: Los Angeles carries an expanded range. You can buy a variety of normally web-exclusive models off the shelf, including releases for games such as &lt;a href="https://www.games-workshop.com/searchResults?N=3281529261%203699755487&amp;amp;utm_source=Warhammer%20Community&amp;amp;utm_medium=Post&amp;amp;utm_campaign=WarhammerStoreCafeLA01022021&amp;amp;utm_content=WarhammerStoreCafeLA01022021" target="_blank" rel="noopener noreferrer"&gt;Adeptus Titanicus&lt;/a&gt; and &lt;a href="https://www.games-workshop.com/searchResults?N=3281529261%20457750697&amp;amp;utm_source=Warhammer%20Community&amp;amp;utm_medium=Post&amp;amp;utm_campaign=WarhammerStoreCafeLA01022021&amp;amp;utm_content=WarhammerStoreCafeLA01022021" target="_blank" rel="noopener noreferrer"&gt;Necromunda&lt;/a&gt;.&nbsp;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;img loading="lazy" decoding="async" class="aligncenter size-full wp-image-120595" src="https://www.warhammer-community.com/wp-content/uploads/2021/02/j83eb0ufnMcPE3iA.jpg" alt="WHCitadel LA Oct14 Content1m" width="1000" height="528" srcset="https://www.warhammer-community.com/wp-content/uploads/2021/02/j83eb0ufnMcPE3iA.jpg 1000w, https://www.warhammer-community.com/wp-content/uploads/2021/02/j83eb0ufnMcPE3iA-500x264.jpg 500w, https://www.warhammer-community.com/wp-content/uploads/2021/02/j83eb0ufnMcPE3iA-428x226.jpg 428w, https://www.warhammer-community.com/wp-content/uploads/2021/02/j83eb0ufnMcPE3iA-846x447.jpg 846w, https://www.warhammer-community.com/wp-content/uploads/2021/02/j83eb0ufnMcPE3iA-665x351.jpg 665w, https://www.warhammer-community.com/wp-content/uploads/2021/02/j83eb0ufnMcPE3iA-490x259.jpg 490w, https://www.warhammer-community.com/wp-content/uploads/2021/02/j83eb0ufnMcPE3iA-330x174.jpg 330w" sizes="(max-width: 1000px) 100vw, 1000px" /&gt;&lt;/p&gt;

&lt;a href='https://www.warhammer-community.com/wp-content/uploads/2021/02/1lHdJk0Tyq4GKdl4.jpg'&gt;&lt;img loading="lazy" decoding="async" width="1000" height="667" src="https://www.warhammer-community.com/wp-content/uploads/2021/02/1lHdJk0Tyq4GKdl4.jpg" class="attachment-full size-full" alt="" srcset="https://www.warhammer-community.com/wp-content/uploads/2021/02/1lHdJk0Tyq4GKdl4.jpg 1000w, https://www.warhammer-community.com/wp-content/uploads/2021/02/1lHdJk0Tyq4GKdl4-500x334.jpg 500w, https://www.warhammer-community.com/wp-content/uploads/2021/02/1lHdJk0Tyq4GKdl4-339x226.jpg 339w, https://www.warhammer-community.com/wp-content/uploads/2021/02/1lHdJk0Tyq4GKdl4-846x564.jpg 846w, https://www.warhammer-community.com/wp-content/uploads/2021/02/1lHdJk0Tyq4GKdl4-665x444.jpg 665w, https://www.warhammer-community.com/wp-content/uploads/2021/02/1lHdJk0Tyq4GKdl4-490x327.jpg 490w, https://www.warhammer-community.com/wp-content/uploads/2021/02/1lHdJk0Tyq4GKdl4-330x220.jpg 330w" sizes="(max-width: 1000px) 100vw, 1000px" /&gt;&lt;/a&gt;
&lt;a href='https://www.warhammer-community.com/wp-content/uploads/2021/02/KkNC4KBBWduVDFR4.jpg'&gt;&lt;img loading="lazy" decoding="async" width="1000" height="667" src="https://www.warhammer-community.com/wp-content/uploads/2021/02/KkNC4KBBWduVDFR4.jpg" class="attachment-full size-full" alt="" srcset="https://www.warhammer-community.com/wp-content/uploads/2021/02/KkNC4KBBWduVDFR4.jpg 1000w, https://www.warhammer-community.com/wp-content/uploads/2021/02/KkNC4KBBWduVDFR4-500x334.jpg 500w, https://www.warhammer-community.com/wp-content/uploads/2021/02/KkNC4KBBWduVDFR4-339x226.jpg 339w, https://www.warhammer-community.com/wp-content/uploads/2021/02/KkNC4KBBWduVDFR4-846x564.jpg 846w, https://www.warhammer-community.com/wp-content/uploads/2021/02/KkNC4KBBWduVDFR4-665x444.jpg 665w, https://www.warhammer-community.com/wp-content/uploads/2021/02/KkNC4KBBWduVDFR4-490x327.jpg 490w, https://www.warhammer-community.com/wp-content/uploads/2021/02/KkNC4KBBWduVDFR4-330x220.jpg 330w" sizes="(max-width: 1000px) 100vw, 1000px" /&gt;&lt;/a&gt;

&lt;p&gt;&lt;b&gt;Forge World&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;The store stocks a variety of popular &lt;a href="https://www.forgeworld.co.uk/FW-Home?utm_source=Warhammer%20Community&amp;amp;utm_medium=Post&amp;amp;utm_campaign=WarhammerStoreCafeLA01022021&amp;amp;utm_content=WarhammerStoreCafeLA01022021" target="_blank" rel="noopener noreferrer"&gt;Forge World&lt;/a&gt; models, and can order you any Forge World kits to the store – with free shipping!* The models available in-store also include a range of kits that you can usually only get at events.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Black Library&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;Fans of Warhammer fiction can find a vast library of books and CDs available to buy, from &lt;a href="https://www.games-workshop.com/searchResults?N=2560222812%203763675593&amp;amp;Nr=AND(sku.siteId%3AGB_gw%2Cproduct.locale%3Aen_GB_gw)&amp;amp;Nrs=collection()%2Frecord%5Bproduct.startDate%20%3C%3D%201612184580000%20and%20product.endDate%20%3E%3D%201612184580000%5D&amp;amp;utm_source=Warhammer%20Community&amp;amp;utm_medium=Post&amp;amp;utm_campaign=WarhammerStoreCafeLA01022021&amp;amp;utm_content=WarhammerStoreCafeLA01022021" target="_blank" rel="noopener noreferrer"&gt;The Horus Heresy&lt;/a&gt; series to tales from the world-that-was, alongside the latest and greatest stories from the Age of Sigmar and the 41st Millennium. You’ll even have the chance to grab copies of limited edition books.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;img loading="lazy" decoding="async" class="aligncenter size-full wp-image-120613" src="https://www.warhammer-community.com/wp-content/uploads/2021/02/25EvefjQpQo0a5PM.jpg" alt="WHCitadel LA Oct14 Content3k" width="1000" height="667" srcset="https://www.warhammer-community.com/wp-content/uploads/2021/02/25EvefjQpQo0a5PM.jpg 1000w, https://www.warhammer-community.com/wp-content/uploads/2021/02/25EvefjQpQo0a5PM-500x334.jpg 500w, https://www.warhammer-community.com/wp-content/uploads/2021/02/25EvefjQpQo0a5PM-339x226.jpg 339w, https://www.warhammer-community.com/wp-content/uploads/2021/02/25EvefjQpQo0a5PM-846x564.jpg 846w, https://www.warhammer-community.com/wp-content/uploads/2021/02/25EvefjQpQo0a5PM-665x444.jpg 665w, https://www.warhammer-community.com/wp-content/uploads/2021/02/25EvefjQpQo0a5PM-490x327.jpg 490w, https://www.warhammer-community.com/wp-content/uploads/2021/02/25EvefjQpQo0a5PM-330x220.jpg 330w" sizes="(max-width: 1000px) 100vw, 1000px" /&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Merchandise&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;You’ll be able to remember your visit to the Warhammer Store &amp;amp; Cafe: Los Angeles with a selection of &lt;a href="https://merch.warhammer.com/?utm_source=Warhammer%20Community&amp;amp;utm_medium=Post&amp;amp;utm_campaign=WarhammerStoreCafeLA01022021&amp;amp;utm_content=WarhammerStoreCafeLA01022021" target="_blank" rel="noopener noreferrer"&gt;Warhammer merchandise&lt;/a&gt;, including art prints, pin badges, and coffee mugs.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Hobby areas&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;The store is a venue for Warhammer gaming and hobby events, with plenty of tables available to play on, as well as dedicated space for &lt;a href="https://www.games-workshop.com/Painting-Modelling?utm_source=Warhammer%20Community&amp;amp;utm_medium=Post&amp;amp;utm_campaign=WarhammerStoreCafeLA01022021&amp;amp;utm_content=WarhammerStoreCafeLA01022021" target="_blank" rel="noopener noreferrer"&gt;building and painting&lt;/a&gt;.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;The cafe&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;Of course, it wouldn’t be much of a store and cafe without a cafe! You can settle down with a hot or cold beverage and a variety of sweet treats –&nbsp;the perfect way to pore over your new codex or lose yourself in an exciting adventure from Black Library.&nbsp;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;The Texas cafe serves such delights as the ‘Prospero’ peach tea and ‘Nuln Oil’ mocha,** as well as a selection of Chaos cookies and warpstone muffins, so there’s plenty to look forward to.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;img loading="lazy" decoding="async" class="aligncenter size-full wp-image-120622" src="https://www.warhammer-community.com/wp-content/uploads/2021/02/OIEF7j57AcFr8Am5.jpg" alt="WHCitadel LA Oct14 Content4b" width="1000" height="667" srcset="https://www.warhammer-community.com/wp-content/uploads/2021/02/OIEF7j57AcFr8Am5.jpg 1000w, https://www.warhammer-community.com/wp-content/uploads/2021/02/OIEF7j57AcFr8Am5-500x334.jpg 500w, https://www.warhammer-community.com/wp-content/uploads/2021/02/OIEF7j57AcFr8Am5-339x226.jpg 339w, https://www.warhammer-community.com/wp-content/uploads/2021/02/OIEF7j57AcFr8Am5-846x564.jpg 846w, https://www.warhammer-community.com/wp-content/uploads/2021/02/OIEF7j57AcFr8Am5-665x444.jpg 665w, https://www.warhammer-community.com/wp-content/uploads/2021/02/OIEF7j57AcFr8Am5-490x327.jpg 490w, https://www.warhammer-community.com/wp-content/uploads/2021/02/OIEF7j57AcFr8Am5-330x220.jpg 330w" sizes="(max-width: 1000px) 100vw, 1000px" /&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;The Warhammer Store &amp;amp; Cafe: Los Angeles is in the town of Monrovia, just down the freeway from the tourist hotspots of the City of Angels. Monrovia is an All-American City – literally. It was awarded the accolade for its civic achievements, and was voted the best downtown area in the San Gabriel Valley for its weekly family festival, community events, and great local shopping – which the new Warhammer store will make even better!&nbsp;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;Monrovia is also within an easy drive of three major airports, making it a perfect hub for Warhammer events.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;The post &lt;a href="https://www.warhammer-community.com/en-us/2021/02/01/introducing-the-warhammer-store-cafe-los-angeles-2/"&gt;Introducing the Warhammer Store &amp;#038; Cafe: Los Angeles&lt;/a&gt; appeared first on &lt;a href="https://www.warhammer-community.com/en-us/"&gt;Warhammer Community&lt;/a&gt;.&lt;/p&gt;
]]&gt;&lt;/content:encoded&gt;
					
		
		
		            &lt;image&gt;https://www.warhammer-community.com/wp-content/uploads/2021/02/kf6SIMEJrL5OJM5g.jpg&lt;/image&gt;
            &lt;image_thumbnail&gt;https://www.warhammer-community.com/wp-content/uploads/2021/02/kf6SIMEJrL5OJM5g-320x320.jpg&lt;/image_thumbnail&gt;
            &lt;image_medium&gt;https://www.warhammer-community.com/wp-content/uploads/2021/02/kf6SIMEJrL5OJM5g-500x310.jpg&lt;/image_medium&gt;
            &lt;image_large&gt;https://www.warhammer-community.com/wp-content/uploads/2021/02/kf6SIMEJrL5OJM5g.jpg&lt;/image_large&gt;
        	&lt;/item&gt;
		&lt;item&gt;
		&lt;title&gt;Introducing the Warhammer Store &amp;#038; Cafe: Los Angeles&lt;/title&gt;
		&lt;link&gt;https://www.warhammer-community.com/en-us/2021/02/01/introducing-the-warhammer-store-cafe-los-angeles/&lt;/link&gt;
		
		&lt;dc:creator&gt;&lt;![CDATA[Nicola Coleman]]&gt;&lt;/dc:creator&gt;
		&lt;pubDate&gt;Mon, 01 Feb 2021 15:27:18 +0000&lt;/pubDate&gt;
				&lt;category&gt;&lt;![CDATA[Invisible]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Black Library]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Warhammer Cafe]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Texas]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Warhammer Citadel]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Hobby]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[New Store]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Games]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Models]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Covid 19]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Merchandise]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Los Angeles]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[Monrovia]]&gt;&lt;/category&gt;
		&lt;category&gt;&lt;![CDATA[San Gabriel Valley]]&gt;&lt;/category&gt;
		&lt;guid isPermaLink="false"&gt;https://www.warhammer-community.com/?p=120664&lt;/guid&gt;

					&lt;description&gt;&lt;![CDATA[&lt;p&gt;A new Warhammer Store &amp;#038; Cafe is coming to southern California – get all details right here.&lt;/p&gt;
&lt;p&gt;The post &lt;a href="https://www.warhammer-community.com/en-us/2021/02/01/introducing-the-warhammer-store-cafe-los-angeles/"&gt;Introducing the Warhammer Store &amp;#038; Cafe: Los Angeles&lt;/a&gt; appeared first on &lt;a href="https://www.warhammer-community.com/en-us/"&gt;Warhammer Community&lt;/a&gt;.&lt;/p&gt;
]]&gt;&lt;/description&gt;
										&lt;content:encoded&gt;&lt;![CDATA[&lt;p&gt;&lt;img loading="lazy" decoding="async" class="aligncenter size-full wp-image-120577" src="https://www.warhammer-community.com/wp-content/uploads/2021/02/wTOjUOEsYwArPrzs.jpg" alt="WHCitadel LA Feb01 Header23bftd" width="1000" height="525" srcset="https://www.warhammer-community.com/wp-content/uploads/2021/02/wTOjUOEsYwArPrzs.jpg 1000w, https://www.warhammer-community.com/wp-content/uploads/2021/02/wTOjUOEsYwArPrzs-500x263.jpg 500w, https://www.warhammer-community.com/wp-content/uploads/2021/02/wTOjUOEsYwArPrzs-430x226.jpg 430w, https://www.warhammer-community.com/wp-content/uploads/2021/02/wTOjUOEsYwArPrzs-846x444.jpg 846w, https://www.warhammer-community.com/wp-content/uploads/2021/02/wTOjUOEsYwArPrzs-665x349.jpg 665w, https://www.warhammer-community.com/wp-content/uploads/2021/02/wTOjUOEsYwArPrzs-490x257.jpg 490w, https://www.warhammer-community.com/wp-content/uploads/2021/02/wTOjUOEsYwArPrzs-330x173.jpg 330w" sizes="(max-width: 1000px) 100vw, 1000px" /&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;Warhammer fans in southern California, rejoice – you’ll soon have a new place to enjoy your favourite hobby. We’re delighted to announce that the Warhammer Store &amp;amp; Cafe: Los Angeles is coming to the area. The exact opening date is yet to be confirmed, but we couldn’t wait to tell you about it.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;This new shop is based on the popular Warhammer Citadel in Grapevine, Texas. Just like its successor, the new LA location offers everything you love about a local Warhammer store and much, much more.&lt;/span&gt;&lt;/p&gt;
&lt;div id="attachment_120640" style="width: 510px" class="wp-caption aligncenter"&gt;&lt;img loading="lazy" decoding="async" aria-describedby="caption-attachment-120640" class="wp-image-120640 size-medium" src="https://www.warhammer-community.com/wp-content/uploads/2021/02/VzmJtK8eCo5EfKdK-500x250.jpg" alt="WHCitadel LA Oct14 Content6a" width="500" height="250" srcset="https://www.warhammer-community.com/wp-content/uploads/2021/02/VzmJtK8eCo5EfKdK-500x250.jpg 500w, https://www.warhammer-community.com/wp-content/uploads/2021/02/VzmJtK8eCo5EfKdK-452x226.jpg 452w, https://www.warhammer-community.com/wp-content/uploads/2021/02/VzmJtK8eCo5EfKdK-846x423.jpg 846w, https://www.warhammer-community.com/wp-content/uploads/2021/02/VzmJtK8eCo5EfKdK-665x333.jpg 665w, https://www.warhammer-community.com/wp-content/uploads/2021/02/VzmJtK8eCo5EfKdK-490x245.jpg 490w, https://www.warhammer-community.com/wp-content/uploads/2021/02/VzmJtK8eCo5EfKdK-330x165.jpg 330w, https://www.warhammer-community.com/wp-content/uploads/2021/02/VzmJtK8eCo5EfKdK.jpg 1000w" sizes="(max-width: 500px) 100vw, 500px" /&gt;&lt;p id="caption-attachment-120640" class="wp-caption-text"&gt;The new location makes its home in Monrovia, a beautiful and bustling shopping and cultural district.&lt;/p&gt;&lt;/div&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Games and models&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;As well as the same amazing boxed games, rulebooks, and models you’d find in other stores, the Warhammer Store &amp;amp; Cafe: Los Angeles carries an expanded range. You can buy a variety of normally web-exclusive models off the shelf, including releases for games such as &lt;a href="https://www.games-workshop.com/searchResults?N=3281529261%203699755487&amp;amp;utm_source=Warhammer%20Community&amp;amp;utm_medium=Post&amp;amp;utm_campaign=WarhammerStoreCafeLA01022021&amp;amp;utm_content=WarhammerStoreCafeLA01022021" target="_blank" rel="noopener noreferrer"&gt;Adeptus Titanicus&lt;/a&gt; and &lt;a href="https://www.games-workshop.com/searchResults?N=3281529261%20457750697&amp;amp;utm_source=Warhammer%20Community&amp;amp;utm_medium=Post&amp;amp;utm_campaign=WarhammerStoreCafeLA01022021&amp;amp;utm_content=WarhammerStoreCafeLA01022021" target="_blank" rel="noopener noreferrer"&gt;Necromunda&lt;/a&gt;.&nbsp;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;img loading="lazy" decoding="async" class="aligncenter size-full wp-image-120595" src="https://www.warhammer-community.com/wp-content/uploads/2021/02/j83eb0ufnMcPE3iA.jpg" alt="WHCitadel LA Oct14 Content1m" width="1000" height="528" srcset="https://www.warhammer-community.com/wp-content/uploads/2021/02/j83eb0ufnMcPE3iA.jpg 1000w, https://www.warhammer-community.com/wp-content/uploads/2021/02/j83eb0ufnMcPE3iA-500x264.jpg 500w, https://www.warhammer-community.com/wp-content/uploads/2021/02/j83eb0ufnMcPE3iA-428x226.jpg 428w, https://www.warhammer-community.com/wp-content/uploads/2021/02/j83eb0ufnMcPE3iA-846x447.jpg 846w, https://www.warhammer-community.com/wp-content/uploads/2021/02/j83eb0ufnMcPE3iA-665x351.jpg 665w, https://www.warhammer-community.com/wp-content/uploads/2021/02/j83eb0ufnMcPE3iA-490x259.jpg 490w, https://www.warhammer-community.com/wp-content/uploads/2021/02/j83eb0ufnMcPE3iA-330x174.jpg 330w" sizes="(max-width: 1000px) 100vw, 1000px" /&gt;&lt;/p&gt;

&lt;a href='https://www.warhammer-community.com/wp-content/uploads/2021/02/1lHdJk0Tyq4GKdl4.jpg'&gt;&lt;img loading="lazy" decoding="async" width="1000" height="667" src="https://www.warhammer-community.com/wp-content/uploads/2021/02/1lHdJk0Tyq4GKdl4.jpg" class="attachment-full size-full" alt="" srcset="https://www.warhammer-community.com/wp-content/uploads/2021/02/1lHdJk0Tyq4GKdl4.jpg 1000w, https://www.warhammer-community.com/wp-content/uploads/2021/02/1lHdJk0Tyq4GKdl4-500x334.jpg 500w, https://www.warhammer-community.com/wp-content/uploads/2021/02/1lHdJk0Tyq4GKdl4-339x226.jpg 339w, https://www.warhammer-community.com/wp-content/uploads/2021/02/1lHdJk0Tyq4GKdl4-846x564.jpg 846w, https://www.warhammer-community.com/wp-content/uploads/2021/02/1lHdJk0Tyq4GKdl4-665x444.jpg 665w, https://www.warhammer-community.com/wp-content/uploads/2021/02/1lHdJk0Tyq4GKdl4-490x327.jpg 490w, https://www.warhammer-community.com/wp-content/uploads/2021/02/1lHdJk0Tyq4GKdl4-330x220.jpg 330w" sizes="(max-width: 1000px) 100vw, 1000px" /&gt;&lt;/a&gt;
&lt;a href='https://www.warhammer-community.com/wp-content/uploads/2021/02/KkNC4KBBWduVDFR4.jpg'&gt;&lt;img loading="lazy" decoding="async" width="1000" height="667" src="https://www.warhammer-community.com/wp-content/uploads/2021/02/KkNC4KBBWduVDFR4.jpg" class="attachment-full size-full" alt="" srcset="https://www.warhammer-community.com/wp-content/uploads/2021/02/KkNC4KBBWduVDFR4.jpg 1000w, https://www.warhammer-community.com/wp-content/uploads/2021/02/KkNC4KBBWduVDFR4-500x334.jpg 500w, https://www.warhammer-community.com/wp-content/uploads/2021/02/KkNC4KBBWduVDFR4-339x226.jpg 339w, https://www.warhammer-community.com/wp-content/uploads/2021/02/KkNC4KBBWduVDFR4-846x564.jpg 846w, https://www.warhammer-community.com/wp-content/uploads/2021/02/KkNC4KBBWduVDFR4-665x444.jpg 665w, https://www.warhammer-community.com/wp-content/uploads/2021/02/KkNC4KBBWduVDFR4-490x327.jpg 490w, https://www.warhammer-community.com/wp-content/uploads/2021/02/KkNC4KBBWduVDFR4-330x220.jpg 330w" sizes="(max-width: 1000px) 100vw, 1000px" /&gt;&lt;/a&gt;

&lt;p&gt;&lt;b&gt;Forge World&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;The store stocks a variety of popular &lt;a href="https://www.forgeworld.co.uk/FW-Home?utm_source=Warhammer%20Community&amp;amp;utm_medium=Post&amp;amp;utm_campaign=WarhammerStoreCafeLA01022021&amp;amp;utm_content=WarhammerStoreCafeLA01022021" target="_blank" rel="noopener noreferrer"&gt;Forge World&lt;/a&gt; models, and can order you any Forge World kits to the store – with free shipping!* The models available in-store also include a range of kits that you can usually only get at events.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Black Library&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;Fans of Warhammer fiction can find a vast library of books and CDs available to buy, from &lt;a href="https://www.games-workshop.com/searchResults?N=2560222812%203763675593&amp;amp;Nr=AND(sku.siteId%3AGB_gw%2Cproduct.locale%3Aen_GB_gw)&amp;amp;Nrs=collection()%2Frecord%5Bproduct.startDate%20%3C%3D%201612184580000%20and%20product.endDate%20%3E%3D%201612184580000%5D&amp;amp;utm_source=Warhammer%20Community&amp;amp;utm_medium=Post&amp;amp;utm_campaign=WarhammerStoreCafeLA01022021&amp;amp;utm_content=WarhammerStoreCafeLA01022021" target="_blank" rel="noopener noreferrer"&gt;The Horus Heresy&lt;/a&gt; series to tales from the world-that-was, alongside the latest and greatest stories from the Age of Sigmar and the 41st Millennium. You’ll even have the chance to grab copies of limited edition books.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;img loading="lazy" decoding="async" class="aligncenter size-full wp-image-120613" src="https://www.warhammer-community.com/wp-content/uploads/2021/02/25EvefjQpQo0a5PM.jpg" alt="WHCitadel LA Oct14 Content3k" width="1000" height="667" srcset="https://www.warhammer-community.com/wp-content/uploads/2021/02/25EvefjQpQo0a5PM.jpg 1000w, https://www.warhammer-community.com/wp-content/uploads/2021/02/25EvefjQpQo0a5PM-500x334.jpg 500w, https://www.warhammer-community.com/wp-content/uploads/2021/02/25EvefjQpQo0a5PM-339x226.jpg 339w, https://www.warhammer-community.com/wp-content/uploads/2021/02/25EvefjQpQo0a5PM-846x564.jpg 846w, https://www.warhammer-community.com/wp-content/uploads/2021/02/25EvefjQpQo0a5PM-665x444.jpg 665w, https://www.warhammer-community.com/wp-content/uploads/2021/02/25EvefjQpQo0a5PM-490x327.jpg 490w, https://www.warhammer-community.com/wp-content/uploads/2021/02/25EvefjQpQo0a5PM-330x220.jpg 330w" sizes="(max-width: 1000px) 100vw, 1000px" /&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Merchandise&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;You’ll be able to remember your visit to the Warhammer Store &amp;amp; Cafe: Los Angeles with a selection of &lt;a href="https://merch.warhammer.com/?utm_source=Warhammer%20Community&amp;amp;utm_medium=Post&amp;amp;utm_campaign=WarhammerStoreCafeLA01022021&amp;amp;utm_content=WarhammerStoreCafeLA01022021" target="_blank" rel="noopener noreferrer"&gt;Warhammer merchandise&lt;/a&gt;, including art prints, pin badges, and coffee mugs.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Hobby areas&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;The store is a venue for Warhammer gaming and hobby events, with plenty of tables available to play on, as well as dedicated space for &lt;a href="https://www.games-workshop.com/Painting-Modelling?utm_source=Warhammer%20Community&amp;amp;utm_medium=Post&amp;amp;utm_campaign=WarhammerStoreCafeLA01022021&amp;amp;utm_content=WarhammerStoreCafeLA01022021" target="_blank" rel="noopener noreferrer"&gt;building and painting&lt;/a&gt;.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;The cafe&lt;/b&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;Of course, it wouldn’t be much of a store and cafe without a cafe! You can settle down with a hot or cold beverage and a variety of sweet treats –&nbsp;the perfect way to pore over your new codex or lose yourself in an exciting adventure from Black Library.&nbsp;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;The Texas cafe serves such delights as the ‘Prospero’ peach tea and ‘Nuln Oil’ mocha,** as well as a selection of Chaos cookies and warpstone muffins, so there’s plenty to look forward to.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;img loading="lazy" decoding="async" class="aligncenter size-full wp-image-120622" src="https://www.warhammer-community.com/wp-content/uploads/2021/02/OIEF7j57AcFr8Am5.jpg" alt="WHCitadel LA Oct14 Content4b" width="1000" height="667" srcset="https://www.warhammer-community.com/wp-content/uploads/2021/02/OIEF7j57AcFr8Am5.jpg 1000w, https://www.warhammer-community.com/wp-content/uploads/2021/02/OIEF7j57AcFr8Am5-500x334.jpg 500w, https://www.warhammer-community.com/wp-content/uploads/2021/02/OIEF7j57AcFr8Am5-339x226.jpg 339w, https://www.warhammer-community.com/wp-content/uploads/2021/02/OIEF7j57AcFr8Am5-846x564.jpg 846w, https://www.warhammer-community.com/wp-content/uploads/2021/02/OIEF7j57AcFr8Am5-665x444.jpg 665w, https://www.warhammer-community.com/wp-content/uploads/2021/02/OIEF7j57AcFr8Am5-490x327.jpg 490w, https://www.warhammer-community.com/wp-content/uploads/2021/02/OIEF7j57AcFr8Am5-330x220.jpg 330w" sizes="(max-width: 1000px) 100vw, 1000px" /&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;The Warhammer Store &amp;amp; Cafe: Los Angeles is in the town of Monrovia, just down the freeway from the tourist hotspots of the City of Angels. Monrovia is an All-American City – literally. It was awarded the accolade for its civic achievements, and was voted the best downtown area in the San Gabriel Valley for its weekly family festival, community events, and great local shopping – which the new Warhammer store will make even better!&nbsp;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400;"&gt;Monrovia is also within an easy drive of three major airports, making it a perfect hub for Warhammer events.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;The post &lt;a href="https://www.warhammer-community.com/en-us/2021/02/01/introducing-the-warhammer-store-cafe-los-angeles/"&gt;Introducing the Warhammer Store &amp;#038; Cafe: Los Angeles&lt;/a&gt; appeared first on &lt;a href="https://www.warhammer-community.com/en-us/"&gt;Warhammer Community&lt;/a&gt;.&lt;/p&gt;
]]&gt;&lt;/content:encoded&gt;
					
		
		
		            &lt;image&gt;https://www.warhammer-community.com/wp-content/uploads/2021/02/kf6SIMEJrL5OJM5g.jpg&lt;/image&gt;
            &lt;image_thumbnail&gt;https://www.warhammer-community.com/wp-content/uploads/2021/02/kf6SIMEJrL5OJM5g-320x320.jpg&lt;/image_thumbnail&gt;
            &lt;image_medium&gt;https://www.warhammer-community.com/wp-content/uploads/2021/02/kf6SIMEJrL5OJM5g-500x310.jpg&lt;/image_medium&gt;
            &lt;image_large&gt;https://www.warhammer-community.com/wp-content/uploads/2021/02/kf6SIMEJrL5OJM5g.jpg&lt;/image_large&gt;
        	&lt;/item&gt;
	&lt;/channel&gt;
&lt;/rss&gt;

&lt;!-- plugin=object-cache-pro client=phpredis metric#hits=1425 metric#misses=30 metric#hit-ratio=97.9 metric#bytes=1849043 metric#prefetches=0 metric#store-reads=108 metric#store-writes=1 metric#store-hits=156 metric#store-misses=26 metric#sql-queries=45 metric#ms-total=249.52 metric#ms-cache=10.17 metric#ms-cache-avg=0.0941 metric#ms-cache-ratio=4.1 --&gt;
</pre></body></html>
"""
